substitutions:
  _IMAGE: "web-client-v2-application/latest"
  _SERVICE_NAME: "web-client-v2-application"
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
        --build-arg NEXT_PUBLIC_BFF_API_URL=$$NEXT_PUBLIC_BFF_API_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_URL=$$NEXT_PUBLIC_SUPABASE_URL \
        --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$$NEXT_PUBLIC_SUPABASE_ANON_KEY \
        -t $_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE -f web/client-v2/Dockerfile .
    secretEnv:
      [
        "NEXT_PUBLIC_BFF_API_URL",
        "NEXT_PUBLIC_SUPABASE_URL",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE",
        "--region",
        "$_REGION",
      ]
images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE
availableSecrets:
  secretManager:
    - versionName: projects/PROJECT_ID/secrets/NEXT_PUBLIC_BFF_API_URL/versions/latest
      env: "NEXT_PUBLIC_BFF_API_URL"
    - versionName: projects/PROJECT_ID/secrets/NEXT_PUBLIC_SUPABASE_URL/versions/latest
      env: "NEXT_PUBLIC_SUPABASE_URL"
    - versionName: projects/PROJECT_ID/secrets/NEXT_PUBLIC_SUPABASE_ANON_KEY/versions/latest
      env: "NEXT_PUBLIC_SUPABASE_ANON_KEY"
