export const NAVIGATION_LISTS = {
  HOME: "/",
  SITE: "/site",
  COMPANY: "/company",
  SUMMARY: "/summary",
  DASHBOARD_TREND: "/dashboard/trend",
  DASHBOARD_SITE: "/dashboard/site",
  DASHBOARD_COMPANY: "/dashboard/company",
  DASHBOARD_SUMMARY: "/dashboard/summary",
  BOOKMARK: "/bookmark",
  ARTICLE_SEARCH: "/article/search",
  ARTICLE_SEARCH_RESULT: "/article/search/result",
  FEED: "/feed",
  MY_FEED_FOLDER: "/my-feed-folder",
  FAVORITE_ARTICLE_FOLDER: "/favorite-article-folder",
};
