// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Articles               string
	Bookmarks              string
	Categories             string
	FavoriteArticleFolders string
	FavoriteArticles       string
	FeedArticleRelations   string
	Feeds                  string
	MyFeedFolders          string
	MyFeeds                string
	Platforms              string
	Profiles               string
	TrendArticles          string
}{
	Articles:               "articles",
	Bookmarks:              "bookmarks",
	Categories:             "categories",
	FavoriteArticleFolders: "favorite_article_folders",
	FavoriteArticles:       "favorite_articles",
	FeedArticleRelations:   "feed_article_relations",
	Feeds:                  "feeds",
	MyFeedFolders:          "my_feed_folders",
	MyFeeds:                "my_feeds",
	Platforms:              "platforms",
	Profiles:               "profiles",
	TrendArticles:          "trend_articles",
}
