// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Articles             string
	Bookmarks            string
	Categories           string
	FeedArticleRelations string
	Feeds                string
	MyFeedLists          string
	MyFeeds              string
	Platforms            string
	Profiles             string
}{
	Articles:             "articles",
	Bookmarks:            "bookmarks",
	Categories:           "categories",
	FeedArticleRelations: "feed_article_relations",
	Feeds:                "feeds",
	MyFeedLists:          "my_feed_lists",
	MyFeeds:              "my_feeds",
	Platforms:            "platforms",
	Profiles:             "profiles",
}
