// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Accounts             string
	Articles             string
	Categories           string
	FeedArticleRelations string
	Feeds                string
	Platforms            string
	Sessions             string
	Users                string
	VerificationTokens   string
}{
	Accounts:             "accounts",
	Articles:             "articles",
	Categories:           "categories",
	FeedArticleRelations: "feed_article_relations",
	Feeds:                "feeds",
	Platforms:            "platforms",
	Sessions:             "sessions",
	Users:                "users",
	VerificationTokens:   "verification_tokens",
}
