// source: bookmark/bookmark.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.checkpicks.bookmark.v1.Bookmark', null, global);
goog.exportSymbol('proto.checkpicks.bookmark.v1.CreateBookmarkRequest', null, global);
goog.exportSymbol('proto.checkpicks.bookmark.v1.CreateBookmarkResponse', null, global);
goog.exportSymbol('proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest', null, global);
goog.exportSymbol('proto.checkpicks.bookmark.v1.GetBookmarkResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.bookmark.v1.GetBookmarkResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.bookmark.v1.GetBookmarkResponse.displayName = 'proto.checkpicks.bookmark.v1.GetBookmarkResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.displayName = 'proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.bookmark.v1.CreateBookmarkResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.bookmark.v1.CreateBookmarkResponse.displayName = 'proto.checkpicks.bookmark.v1.CreateBookmarkResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.bookmark.v1.CreateBookmarkRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.bookmark.v1.CreateBookmarkRequest.displayName = 'proto.checkpicks.bookmark.v1.CreateBookmarkRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.bookmark.v1.Bookmark = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.bookmark.v1.Bookmark, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.bookmark.v1.Bookmark.displayName = 'proto.checkpicks.bookmark.v1.Bookmark';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.bookmark.v1.GetBookmarkResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    bookmark: (f = msg.getBookmark()) && proto.checkpicks.bookmark.v1.Bookmark.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkResponse}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.bookmark.v1.GetBookmarkResponse;
  return proto.checkpicks.bookmark.v1.GetBookmarkResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkResponse}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.bookmark.v1.Bookmark;
      reader.readMessage(value,proto.checkpicks.bookmark.v1.Bookmark.deserializeBinaryFromReader);
      msg.setBookmark(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.bookmark.v1.GetBookmarkResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBookmark();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.bookmark.v1.Bookmark.serializeBinaryToWriter
    );
  }
};


/**
 * optional Bookmark bookmark = 1;
 * @return {?proto.checkpicks.bookmark.v1.Bookmark}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.getBookmark = function() {
  return /** @type{?proto.checkpicks.bookmark.v1.Bookmark} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.bookmark.v1.Bookmark, 1));
};


/**
 * @param {?proto.checkpicks.bookmark.v1.Bookmark|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkResponse} returns this
*/
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.setBookmark = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkResponse} returns this
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.clearBookmark = function() {
  return this.setBookmark(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.GetBookmarkResponse.prototype.hasBookmark = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    articleId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest;
  return proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArticleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string article_id = 1;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.getArticleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest} returns this
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.setArticleId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest} returns this
 */
proto.checkpicks.bookmark.v1.GetBookmarkByArticleIDRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.bookmark.v1.CreateBookmarkResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    bookmark: (f = msg.getBookmark()) && proto.checkpicks.bookmark.v1.Bookmark.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.bookmark.v1.CreateBookmarkResponse;
  return proto.checkpicks.bookmark.v1.CreateBookmarkResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.bookmark.v1.Bookmark;
      reader.readMessage(value,proto.checkpicks.bookmark.v1.Bookmark.deserializeBinaryFromReader);
      msg.setBookmark(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.bookmark.v1.CreateBookmarkResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBookmark();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.bookmark.v1.Bookmark.serializeBinaryToWriter
    );
  }
};


/**
 * optional Bookmark bookmark = 1;
 * @return {?proto.checkpicks.bookmark.v1.Bookmark}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.getBookmark = function() {
  return /** @type{?proto.checkpicks.bookmark.v1.Bookmark} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.bookmark.v1.Bookmark, 1));
};


/**
 * @param {?proto.checkpicks.bookmark.v1.Bookmark|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse} returns this
*/
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.setBookmark = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkResponse} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.clearBookmark = function() {
  return this.setBookmark(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkResponse.prototype.hasBookmark = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.bookmark.v1.CreateBookmarkRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    articleId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    platformId: (f = msg.getPlatformId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    title: jspb.Message.getFieldWithDefault(msg, 4, ""),
    description: jspb.Message.getFieldWithDefault(msg, 5, ""),
    articleUrl: jspb.Message.getFieldWithDefault(msg, 6, ""),
    thumbnailUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    publishedAt: (f = msg.getPublishedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    platformName: jspb.Message.getFieldWithDefault(msg, 9, ""),
    platformUrl: jspb.Message.getFieldWithDefault(msg, 10, ""),
    platformFaviconUrl: jspb.Message.getFieldWithDefault(msg, 11, ""),
    isEng: jspb.Message.getBooleanFieldWithDefault(msg, 12, false),
    isRead: jspb.Message.getBooleanFieldWithDefault(msg, 13, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.bookmark.v1.CreateBookmarkRequest;
  return proto.checkpicks.bookmark.v1.CreateBookmarkRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPlatformId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleUrl(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnailUrl(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublishedAt(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformName(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformUrl(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformFaviconUrl(value);
      break;
    case 12:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsEng(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRead(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.bookmark.v1.CreateBookmarkRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArticleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPlatformId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getArticleUrl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getThumbnailUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getPublishedAt();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPlatformName();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getPlatformUrl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getPlatformFaviconUrl();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getIsEng();
  if (f) {
    writer.writeBool(
      12,
      f
    );
  }
  f = message.getIsRead();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
};


/**
 * optional string article_id = 1;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getArticleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setArticleId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue platform_id = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getPlatformId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
*/
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setPlatformId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.clearPlatformId = function() {
  return this.setPlatformId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.hasPlatformId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string title = 4;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string article_url = 6;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getArticleUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setArticleUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string thumbnail_url = 7;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getThumbnailUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setThumbnailUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional google.protobuf.Timestamp published_at = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getPublishedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
*/
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setPublishedAt = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.clearPublishedAt = function() {
  return this.setPublishedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.hasPublishedAt = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional string platform_name = 9;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getPlatformName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setPlatformName = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string platform_url = 10;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getPlatformUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setPlatformUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string platform_favicon_url = 11;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getPlatformFaviconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setPlatformFaviconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional bool is_eng = 12;
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getIsEng = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 12, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setIsEng = function(value) {
  return jspb.Message.setProto3BooleanField(this, 12, value);
};


/**
 * optional bool is_read = 13;
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.getIsRead = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.bookmark.v1.CreateBookmarkRequest} returns this
 */
proto.checkpicks.bookmark.v1.CreateBookmarkRequest.prototype.setIsRead = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.bookmark.v1.Bookmark.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.bookmark.v1.Bookmark} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.Bookmark.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    articleId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    platformId: (f = msg.getPlatformId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    title: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    articleUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    thumbnailUrl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    publishedAt: (f = msg.getPublishedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    platformName: jspb.Message.getFieldWithDefault(msg, 10, ""),
    platformUrl: jspb.Message.getFieldWithDefault(msg, 11, ""),
    platformFaviconUrl: jspb.Message.getFieldWithDefault(msg, 12, ""),
    isEng: jspb.Message.getBooleanFieldWithDefault(msg, 13, false),
    isRead: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark}
 */
proto.checkpicks.bookmark.v1.Bookmark.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.bookmark.v1.Bookmark;
  return proto.checkpicks.bookmark.v1.Bookmark.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.bookmark.v1.Bookmark} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark}
 */
proto.checkpicks.bookmark.v1.Bookmark.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPlatformId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleUrl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnailUrl(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublishedAt(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformName(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformUrl(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformFaviconUrl(value);
      break;
    case 13:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsEng(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRead(value);
      break;
    case 15:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 16:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.bookmark.v1.Bookmark.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.bookmark.v1.Bookmark} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.bookmark.v1.Bookmark.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArticleId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPlatformId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getArticleUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getThumbnailUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPublishedAt();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPlatformName();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getPlatformUrl();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getPlatformFaviconUrl();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getIsEng();
  if (f) {
    writer.writeBool(
      13,
      f
    );
  }
  f = message.getIsRead();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string article_id = 2;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getArticleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setArticleId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string user_id = 3;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.StringValue platform_id = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getPlatformId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
*/
proto.checkpicks.bookmark.v1.Bookmark.prototype.setPlatformId = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.clearPlatformId = function() {
  return this.setPlatformId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.hasPlatformId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string title = 5;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string article_url = 7;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getArticleUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setArticleUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string thumbnail_url = 8;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getThumbnailUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setThumbnailUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional google.protobuf.Timestamp published_at = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getPublishedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
*/
proto.checkpicks.bookmark.v1.Bookmark.prototype.setPublishedAt = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.clearPublishedAt = function() {
  return this.setPublishedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.hasPublishedAt = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string platform_name = 10;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getPlatformName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setPlatformName = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string platform_url = 11;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getPlatformUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setPlatformUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string platform_favicon_url = 12;
 * @return {string}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getPlatformFaviconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setPlatformFaviconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional bool is_eng = 13;
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getIsEng = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 13, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setIsEng = function(value) {
  return jspb.Message.setProto3BooleanField(this, 13, value);
};


/**
 * optional bool is_read = 14;
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getIsRead = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.setIsRead = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 15;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 15));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
*/
proto.checkpicks.bookmark.v1.Bookmark.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 16;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 16));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
*/
proto.checkpicks.bookmark.v1.Bookmark.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.bookmark.v1.Bookmark} returns this
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.bookmark.v1.Bookmark.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 16) != null;
};


goog.object.extend(exports, proto.checkpicks.bookmark.v1);
