// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/YukiOnishi1129/checkpicks-protocol-buffers/checkpicks-rpc-go/grpc/favorite (interfaces: FavoriteServiceClient,FavoriteServiceServer,UnsafeFavoriteServiceServer)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	favorite "github.com/YukiOnishi1129/checkpicks-protocol-buffers/checkpicks-rpc-go/grpc/favorite"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockFavoriteServiceClient is a mock of FavoriteServiceClient interface.
type MockFavoriteServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteServiceClientMockRecorder
}

// MockFavoriteServiceClientMockRecorder is the mock recorder for MockFavoriteServiceClient.
type MockFavoriteServiceClientMockRecorder struct {
	mock *MockFavoriteServiceClient
}

// NewMockFavoriteServiceClient creates a new mock instance.
func NewMockFavoriteServiceClient(ctrl *gomock.Controller) *MockFavoriteServiceClient {
	mock := &MockFavoriteServiceClient{ctrl: ctrl}
	mock.recorder = &MockFavoriteServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteServiceClient) EXPECT() *MockFavoriteServiceClientMockRecorder {
	return m.recorder
}

// CreateFavoriteArticle mocks base method.
func (m *MockFavoriteServiceClient) CreateFavoriteArticle(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleRequest, arg2 ...grpc.CallOption) (*favorite.CreateFavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFavoriteArticle", varargs...)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticle indicates an expected call of CreateFavoriteArticle.
func (mr *MockFavoriteServiceClientMockRecorder) CreateFavoriteArticle(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticle", reflect.TypeOf((*MockFavoriteServiceClient)(nil).CreateFavoriteArticle), varargs...)
}

// CreateFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceClient) CreateFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleFolderRequest, arg2 ...grpc.CallOption) (*favorite.CreateFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFavoriteArticleFolder", varargs...)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticleFolder indicates an expected call of CreateFavoriteArticleFolder.
func (mr *MockFavoriteServiceClientMockRecorder) CreateFavoriteArticleFolder(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceClient)(nil).CreateFavoriteArticleFolder), varargs...)
}

// CreateFavoriteArticleForUploadArticle mocks base method.
func (m *MockFavoriteServiceClient) CreateFavoriteArticleForUploadArticle(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleForUploadArticleRequest, arg2 ...grpc.CallOption) (*favorite.CreateFavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateFavoriteArticleForUploadArticle", varargs...)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticleForUploadArticle indicates an expected call of CreateFavoriteArticleForUploadArticle.
func (mr *MockFavoriteServiceClientMockRecorder) CreateFavoriteArticleForUploadArticle(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticleForUploadArticle", reflect.TypeOf((*MockFavoriteServiceClient)(nil).CreateFavoriteArticleForUploadArticle), varargs...)
}

// CreateMultiFavoriteArticlesForUploadArticle mocks base method.
func (m *MockFavoriteServiceClient) CreateMultiFavoriteArticlesForUploadArticle(arg0 context.Context, arg1 *favorite.CreateMultiFavoriteArticlesForUploadArticleRequest, arg2 ...grpc.CallOption) (*favorite.CreateMultiFavoriteArticlesForUploadArticleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateMultiFavoriteArticlesForUploadArticle", varargs...)
	ret0, _ := ret[0].(*favorite.CreateMultiFavoriteArticlesForUploadArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultiFavoriteArticlesForUploadArticle indicates an expected call of CreateMultiFavoriteArticlesForUploadArticle.
func (mr *MockFavoriteServiceClientMockRecorder) CreateMultiFavoriteArticlesForUploadArticle(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiFavoriteArticlesForUploadArticle", reflect.TypeOf((*MockFavoriteServiceClient)(nil).CreateMultiFavoriteArticlesForUploadArticle), varargs...)
}

// DeleteFavoriteArticle mocks base method.
func (m *MockFavoriteServiceClient) DeleteFavoriteArticle(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFavoriteArticle", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticle indicates an expected call of DeleteFavoriteArticle.
func (mr *MockFavoriteServiceClientMockRecorder) DeleteFavoriteArticle(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticle", reflect.TypeOf((*MockFavoriteServiceClient)(nil).DeleteFavoriteArticle), varargs...)
}

// DeleteFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceClient) DeleteFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleFolderRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFavoriteArticleFolder", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticleFolder indicates an expected call of DeleteFavoriteArticleFolder.
func (mr *MockFavoriteServiceClientMockRecorder) DeleteFavoriteArticleFolder(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceClient)(nil).DeleteFavoriteArticleFolder), varargs...)
}

// DeleteFavoriteArticlesByArticleId mocks base method.
func (m *MockFavoriteServiceClient) DeleteFavoriteArticlesByArticleId(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleByArticleIdRequest, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteFavoriteArticlesByArticleId", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticlesByArticleId indicates an expected call of DeleteFavoriteArticlesByArticleId.
func (mr *MockFavoriteServiceClientMockRecorder) DeleteFavoriteArticlesByArticleId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticlesByArticleId", reflect.TypeOf((*MockFavoriteServiceClient)(nil).DeleteFavoriteArticlesByArticleId), varargs...)
}

// GetFavoriteAllFolderArticles mocks base method.
func (m *MockFavoriteServiceClient) GetFavoriteAllFolderArticles(arg0 context.Context, arg1 *favorite.GetFavoriteAllFolderArticlesRequest, arg2 ...grpc.CallOption) (*favorite.GetFavoriteAllFolderArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoriteAllFolderArticles", varargs...)
	ret0, _ := ret[0].(*favorite.GetFavoriteAllFolderArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteAllFolderArticles indicates an expected call of GetFavoriteAllFolderArticles.
func (mr *MockFavoriteServiceClientMockRecorder) GetFavoriteAllFolderArticles(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteAllFolderArticles", reflect.TypeOf((*MockFavoriteServiceClient)(nil).GetFavoriteAllFolderArticles), varargs...)
}

// GetFavoriteArticleFolderById mocks base method.
func (m *MockFavoriteServiceClient) GetFavoriteArticleFolderById(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFolderByIdRequest, arg2 ...grpc.CallOption) (*favorite.GetFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoriteArticleFolderById", varargs...)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFolderById indicates an expected call of GetFavoriteArticleFolderById.
func (mr *MockFavoriteServiceClientMockRecorder) GetFavoriteArticleFolderById(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFolderById", reflect.TypeOf((*MockFavoriteServiceClient)(nil).GetFavoriteArticleFolderById), varargs...)
}

// GetFavoriteArticleFolders mocks base method.
func (m *MockFavoriteServiceClient) GetFavoriteArticleFolders(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFoldersRequest, arg2 ...grpc.CallOption) (*favorite.GetFavoriteArticleFoldersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoriteArticleFolders", varargs...)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFoldersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFolders indicates an expected call of GetFavoriteArticleFolders.
func (mr *MockFavoriteServiceClientMockRecorder) GetFavoriteArticleFolders(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFolders", reflect.TypeOf((*MockFavoriteServiceClient)(nil).GetFavoriteArticleFolders), varargs...)
}

// GetFavoriteArticleFoldersByArticleId mocks base method.
func (m *MockFavoriteServiceClient) GetFavoriteArticleFoldersByArticleId(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFoldersByArticleIdRequest, arg2 ...grpc.CallOption) (*favorite.GetFavoriteArticleFoldersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoriteArticleFoldersByArticleId", varargs...)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFoldersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFoldersByArticleId indicates an expected call of GetFavoriteArticleFoldersByArticleId.
func (mr *MockFavoriteServiceClientMockRecorder) GetFavoriteArticleFoldersByArticleId(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFoldersByArticleId", reflect.TypeOf((*MockFavoriteServiceClient)(nil).GetFavoriteArticleFoldersByArticleId), varargs...)
}

// GetFavoriteArticles mocks base method.
func (m *MockFavoriteServiceClient) GetFavoriteArticles(arg0 context.Context, arg1 *favorite.GetFavoriteArticlesRequest, arg2 ...grpc.CallOption) (*favorite.GetFavoriteArticlesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetFavoriteArticles", varargs...)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticles indicates an expected call of GetFavoriteArticles.
func (mr *MockFavoriteServiceClientMockRecorder) GetFavoriteArticles(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticles", reflect.TypeOf((*MockFavoriteServiceClient)(nil).GetFavoriteArticles), varargs...)
}

// UpdateFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceClient) UpdateFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.UpdateFavoriteArticleFolderRequest, arg2 ...grpc.CallOption) (*favorite.UpdateFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateFavoriteArticleFolder", varargs...)
	ret0, _ := ret[0].(*favorite.UpdateFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFavoriteArticleFolder indicates an expected call of UpdateFavoriteArticleFolder.
func (mr *MockFavoriteServiceClientMockRecorder) UpdateFavoriteArticleFolder(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceClient)(nil).UpdateFavoriteArticleFolder), varargs...)
}

// MockFavoriteServiceServer is a mock of FavoriteServiceServer interface.
type MockFavoriteServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockFavoriteServiceServerMockRecorder
}

// MockFavoriteServiceServerMockRecorder is the mock recorder for MockFavoriteServiceServer.
type MockFavoriteServiceServerMockRecorder struct {
	mock *MockFavoriteServiceServer
}

// NewMockFavoriteServiceServer creates a new mock instance.
func NewMockFavoriteServiceServer(ctrl *gomock.Controller) *MockFavoriteServiceServer {
	mock := &MockFavoriteServiceServer{ctrl: ctrl}
	mock.recorder = &MockFavoriteServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFavoriteServiceServer) EXPECT() *MockFavoriteServiceServerMockRecorder {
	return m.recorder
}

// CreateFavoriteArticle mocks base method.
func (m *MockFavoriteServiceServer) CreateFavoriteArticle(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleRequest) (*favorite.CreateFavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavoriteArticle", arg0, arg1)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticle indicates an expected call of CreateFavoriteArticle.
func (mr *MockFavoriteServiceServerMockRecorder) CreateFavoriteArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticle", reflect.TypeOf((*MockFavoriteServiceServer)(nil).CreateFavoriteArticle), arg0, arg1)
}

// CreateFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceServer) CreateFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleFolderRequest) (*favorite.CreateFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavoriteArticleFolder", arg0, arg1)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticleFolder indicates an expected call of CreateFavoriteArticleFolder.
func (mr *MockFavoriteServiceServerMockRecorder) CreateFavoriteArticleFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceServer)(nil).CreateFavoriteArticleFolder), arg0, arg1)
}

// CreateFavoriteArticleForUploadArticle mocks base method.
func (m *MockFavoriteServiceServer) CreateFavoriteArticleForUploadArticle(arg0 context.Context, arg1 *favorite.CreateFavoriteArticleForUploadArticleRequest) (*favorite.CreateFavoriteArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFavoriteArticleForUploadArticle", arg0, arg1)
	ret0, _ := ret[0].(*favorite.CreateFavoriteArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFavoriteArticleForUploadArticle indicates an expected call of CreateFavoriteArticleForUploadArticle.
func (mr *MockFavoriteServiceServerMockRecorder) CreateFavoriteArticleForUploadArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFavoriteArticleForUploadArticle", reflect.TypeOf((*MockFavoriteServiceServer)(nil).CreateFavoriteArticleForUploadArticle), arg0, arg1)
}

// CreateMultiFavoriteArticlesForUploadArticle mocks base method.
func (m *MockFavoriteServiceServer) CreateMultiFavoriteArticlesForUploadArticle(arg0 context.Context, arg1 *favorite.CreateMultiFavoriteArticlesForUploadArticleRequest) (*favorite.CreateMultiFavoriteArticlesForUploadArticleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiFavoriteArticlesForUploadArticle", arg0, arg1)
	ret0, _ := ret[0].(*favorite.CreateMultiFavoriteArticlesForUploadArticleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultiFavoriteArticlesForUploadArticle indicates an expected call of CreateMultiFavoriteArticlesForUploadArticle.
func (mr *MockFavoriteServiceServerMockRecorder) CreateMultiFavoriteArticlesForUploadArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiFavoriteArticlesForUploadArticle", reflect.TypeOf((*MockFavoriteServiceServer)(nil).CreateMultiFavoriteArticlesForUploadArticle), arg0, arg1)
}

// DeleteFavoriteArticle mocks base method.
func (m *MockFavoriteServiceServer) DeleteFavoriteArticle(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavoriteArticle", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticle indicates an expected call of DeleteFavoriteArticle.
func (mr *MockFavoriteServiceServerMockRecorder) DeleteFavoriteArticle(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticle", reflect.TypeOf((*MockFavoriteServiceServer)(nil).DeleteFavoriteArticle), arg0, arg1)
}

// DeleteFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceServer) DeleteFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleFolderRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavoriteArticleFolder", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticleFolder indicates an expected call of DeleteFavoriteArticleFolder.
func (mr *MockFavoriteServiceServerMockRecorder) DeleteFavoriteArticleFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceServer)(nil).DeleteFavoriteArticleFolder), arg0, arg1)
}

// DeleteFavoriteArticlesByArticleId mocks base method.
func (m *MockFavoriteServiceServer) DeleteFavoriteArticlesByArticleId(arg0 context.Context, arg1 *favorite.DeleteFavoriteArticleByArticleIdRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFavoriteArticlesByArticleId", arg0, arg1)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFavoriteArticlesByArticleId indicates an expected call of DeleteFavoriteArticlesByArticleId.
func (mr *MockFavoriteServiceServerMockRecorder) DeleteFavoriteArticlesByArticleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFavoriteArticlesByArticleId", reflect.TypeOf((*MockFavoriteServiceServer)(nil).DeleteFavoriteArticlesByArticleId), arg0, arg1)
}

// GetFavoriteAllFolderArticles mocks base method.
func (m *MockFavoriteServiceServer) GetFavoriteAllFolderArticles(arg0 context.Context, arg1 *favorite.GetFavoriteAllFolderArticlesRequest) (*favorite.GetFavoriteAllFolderArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteAllFolderArticles", arg0, arg1)
	ret0, _ := ret[0].(*favorite.GetFavoriteAllFolderArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteAllFolderArticles indicates an expected call of GetFavoriteAllFolderArticles.
func (mr *MockFavoriteServiceServerMockRecorder) GetFavoriteAllFolderArticles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteAllFolderArticles", reflect.TypeOf((*MockFavoriteServiceServer)(nil).GetFavoriteAllFolderArticles), arg0, arg1)
}

// GetFavoriteArticleFolderById mocks base method.
func (m *MockFavoriteServiceServer) GetFavoriteArticleFolderById(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFolderByIdRequest) (*favorite.GetFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteArticleFolderById", arg0, arg1)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFolderById indicates an expected call of GetFavoriteArticleFolderById.
func (mr *MockFavoriteServiceServerMockRecorder) GetFavoriteArticleFolderById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFolderById", reflect.TypeOf((*MockFavoriteServiceServer)(nil).GetFavoriteArticleFolderById), arg0, arg1)
}

// GetFavoriteArticleFolders mocks base method.
func (m *MockFavoriteServiceServer) GetFavoriteArticleFolders(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFoldersRequest) (*favorite.GetFavoriteArticleFoldersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteArticleFolders", arg0, arg1)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFoldersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFolders indicates an expected call of GetFavoriteArticleFolders.
func (mr *MockFavoriteServiceServerMockRecorder) GetFavoriteArticleFolders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFolders", reflect.TypeOf((*MockFavoriteServiceServer)(nil).GetFavoriteArticleFolders), arg0, arg1)
}

// GetFavoriteArticleFoldersByArticleId mocks base method.
func (m *MockFavoriteServiceServer) GetFavoriteArticleFoldersByArticleId(arg0 context.Context, arg1 *favorite.GetFavoriteArticleFoldersByArticleIdRequest) (*favorite.GetFavoriteArticleFoldersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteArticleFoldersByArticleId", arg0, arg1)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticleFoldersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticleFoldersByArticleId indicates an expected call of GetFavoriteArticleFoldersByArticleId.
func (mr *MockFavoriteServiceServerMockRecorder) GetFavoriteArticleFoldersByArticleId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticleFoldersByArticleId", reflect.TypeOf((*MockFavoriteServiceServer)(nil).GetFavoriteArticleFoldersByArticleId), arg0, arg1)
}

// GetFavoriteArticles mocks base method.
func (m *MockFavoriteServiceServer) GetFavoriteArticles(arg0 context.Context, arg1 *favorite.GetFavoriteArticlesRequest) (*favorite.GetFavoriteArticlesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavoriteArticles", arg0, arg1)
	ret0, _ := ret[0].(*favorite.GetFavoriteArticlesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavoriteArticles indicates an expected call of GetFavoriteArticles.
func (mr *MockFavoriteServiceServerMockRecorder) GetFavoriteArticles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteArticles", reflect.TypeOf((*MockFavoriteServiceServer)(nil).GetFavoriteArticles), arg0, arg1)
}

// UpdateFavoriteArticleFolder mocks base method.
func (m *MockFavoriteServiceServer) UpdateFavoriteArticleFolder(arg0 context.Context, arg1 *favorite.UpdateFavoriteArticleFolderRequest) (*favorite.UpdateFavoriteArticleFolderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFavoriteArticleFolder", arg0, arg1)
	ret0, _ := ret[0].(*favorite.UpdateFavoriteArticleFolderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFavoriteArticleFolder indicates an expected call of UpdateFavoriteArticleFolder.
func (mr *MockFavoriteServiceServerMockRecorder) UpdateFavoriteArticleFolder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFavoriteArticleFolder", reflect.TypeOf((*MockFavoriteServiceServer)(nil).UpdateFavoriteArticleFolder), arg0, arg1)
}

// MockUnsafeFavoriteServiceServer is a mock of UnsafeFavoriteServiceServer interface.
type MockUnsafeFavoriteServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeFavoriteServiceServerMockRecorder
}

// MockUnsafeFavoriteServiceServerMockRecorder is the mock recorder for MockUnsafeFavoriteServiceServer.
type MockUnsafeFavoriteServiceServerMockRecorder struct {
	mock *MockUnsafeFavoriteServiceServer
}

// NewMockUnsafeFavoriteServiceServer creates a new mock instance.
func NewMockUnsafeFavoriteServiceServer(ctrl *gomock.Controller) *MockUnsafeFavoriteServiceServer {
	mock := &MockUnsafeFavoriteServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeFavoriteServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeFavoriteServiceServer) EXPECT() *MockUnsafeFavoriteServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedFavoriteServiceServer mocks base method.
func (m *MockUnsafeFavoriteServiceServer) mustEmbedUnimplementedFavoriteServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedFavoriteServiceServer")
}

// mustEmbedUnimplementedFavoriteServiceServer indicates an expected call of mustEmbedUnimplementedFavoriteServiceServer.
func (mr *MockUnsafeFavoriteServiceServerMockRecorder) mustEmbedUnimplementedFavoriteServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedFavoriteServiceServer", reflect.TypeOf((*MockUnsafeFavoriteServiceServer)(nil).mustEmbedUnimplementedFavoriteServiceServer))
}
