// source: my_feed/my_feed.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var content_content_pb = require('../content/content_pb.js');
goog.object.extend(proto, content_content_pb);
goog.exportSymbol('proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest', null, global);
goog.exportSymbol('proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse', null, global);
goog.exportSymbol('proto.checkpicks.my_feed.v1.MyFeedFolder', null, global);
goog.exportSymbol('proto.checkpicks.my_feed.v1.MyFeedFolderEdge', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.repeatedFields_, null);
};
goog.inherits(proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.displayName = 'proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.displayName = 'proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.my_feed.v1.MyFeedFolderEdge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.my_feed.v1.MyFeedFolderEdge.displayName = 'proto.checkpicks.my_feed.v1.MyFeedFolderEdge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.my_feed.v1.MyFeedFolder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.checkpicks.my_feed.v1.MyFeedFolder.repeatedFields_, null);
};
goog.inherits(proto.checkpicks.my_feed.v1.MyFeedFolder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.my_feed.v1.MyFeedFolder.displayName = 'proto.checkpicks.my_feed.v1.MyFeedFolder';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    myFeedFolderEdgesList: jspb.Message.toObjectList(msg.getMyFeedFolderEdgesList(),
    proto.checkpicks.my_feed.v1.MyFeedFolderEdge.toObject, includeInstance),
    pageInfo: (f = msg.getPageInfo()) && content_content_pb.PageInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse;
  return proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.my_feed.v1.MyFeedFolderEdge;
      reader.readMessage(value,proto.checkpicks.my_feed.v1.MyFeedFolderEdge.deserializeBinaryFromReader);
      msg.addMyFeedFolderEdges(value);
      break;
    case 2:
      var value = new content_content_pb.PageInfo;
      reader.readMessage(value,content_content_pb.PageInfo.deserializeBinaryFromReader);
      msg.setPageInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMyFeedFolderEdgesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.checkpicks.my_feed.v1.MyFeedFolderEdge.serializeBinaryToWriter
    );
  }
  f = message.getPageInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      content_content_pb.PageInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated MyFeedFolderEdge my_feed_folder_edges = 1;
 * @return {!Array<!proto.checkpicks.my_feed.v1.MyFeedFolderEdge>}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.getMyFeedFolderEdgesList = function() {
  return /** @type{!Array<!proto.checkpicks.my_feed.v1.MyFeedFolderEdge>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.checkpicks.my_feed.v1.MyFeedFolderEdge, 1));
};


/**
 * @param {!Array<!proto.checkpicks.my_feed.v1.MyFeedFolderEdge>} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} returns this
*/
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.setMyFeedFolderEdgesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.addMyFeedFolderEdges = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.checkpicks.my_feed.v1.MyFeedFolderEdge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.clearMyFeedFolderEdgesList = function() {
  return this.setMyFeedFolderEdgesList([]);
};


/**
 * optional checkpicks.content.v1.PageInfo page_info = 2;
 * @return {?proto.checkpicks.content.v1.PageInfo}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.getPageInfo = function() {
  return /** @type{?proto.checkpicks.content.v1.PageInfo} */ (
    jspb.Message.getWrapperField(this, content_content_pb.PageInfo, 2));
};


/**
 * @param {?proto.checkpicks.content.v1.PageInfo|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} returns this
*/
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.setPageInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.clearPageInfo = function() {
  return this.setPageInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersResponse.prototype.hasPageInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    keyword: (f = msg.getKeyword()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    cursor: jspb.Message.getFieldWithDefault(msg, 3, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest;
  return proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setKeyword(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKeyword();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.StringValue keyword = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.getKeyword = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} returns this
*/
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.setKeyword = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.clearKeyword = function() {
  return this.setKeyword(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.hasKeyword = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string cursor = 3;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 limit = 4;
 * @return {number}
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest} returns this
 */
proto.checkpicks.my_feed.v1.GetMyFeedFoldersRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.my_feed.v1.MyFeedFolderEdge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.toObject = function(includeInstance, msg) {
  var f, obj = {
    node: (f = msg.getNode()) && proto.checkpicks.my_feed.v1.MyFeedFolder.toObject(includeInstance, f),
    cursor: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.my_feed.v1.MyFeedFolderEdge;
  return proto.checkpicks.my_feed.v1.MyFeedFolderEdge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.my_feed.v1.MyFeedFolder;
      reader.readMessage(value,proto.checkpicks.my_feed.v1.MyFeedFolder.deserializeBinaryFromReader);
      msg.setNode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.my_feed.v1.MyFeedFolderEdge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.my_feed.v1.MyFeedFolder.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional MyFeedFolder node = 1;
 * @return {?proto.checkpicks.my_feed.v1.MyFeedFolder}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.getNode = function() {
  return /** @type{?proto.checkpicks.my_feed.v1.MyFeedFolder} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.my_feed.v1.MyFeedFolder, 1));
};


/**
 * @param {?proto.checkpicks.my_feed.v1.MyFeedFolder|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} returns this
*/
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.setNode = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.clearNode = function() {
  return this.setNode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.hasNode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string cursor = 2;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolderEdge} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolderEdge.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.my_feed.v1.MyFeedFolder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    feedsList: jspb.Message.toObjectList(msg.getFeedsList(),
    content_content_pb.Feed.toObject, includeInstance),
    description: (f = msg.getDescription()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.my_feed.v1.MyFeedFolder;
  return proto.checkpicks.my_feed.v1.MyFeedFolder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = new content_content_pb.Feed;
      reader.readMessage(value,content_content_pb.Feed.deserializeBinaryFromReader);
      msg.addFeeds(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setDescription(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.my_feed.v1.MyFeedFolder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.my_feed.v1.MyFeedFolder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFeedsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      content_content_pb.Feed.serializeBinaryToWriter
    );
  }
  f = message.getDescription();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 3;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated checkpicks.content.v1.Feed feeds = 4;
 * @return {!Array<!proto.checkpicks.content.v1.Feed>}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getFeedsList = function() {
  return /** @type{!Array<!proto.checkpicks.content.v1.Feed>} */ (
    jspb.Message.getRepeatedWrapperField(this, content_content_pb.Feed, 4));
};


/**
 * @param {!Array<!proto.checkpicks.content.v1.Feed>} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
*/
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setFeedsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.checkpicks.content.v1.Feed=} opt_value
 * @param {number=} opt_index
 * @return {!proto.checkpicks.content.v1.Feed}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.addFeeds = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.checkpicks.content.v1.Feed, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.clearFeedsList = function() {
  return this.setFeedsList([]);
};


/**
 * optional google.protobuf.StringValue description = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getDescription = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
*/
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setDescription = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.clearDescription = function() {
  return this.setDescription(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp created_at = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
*/
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
*/
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.my_feed.v1.MyFeedFolder} returns this
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.my_feed.v1.MyFeedFolder.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 7) != null;
};


goog.object.extend(exports, proto.checkpicks.my_feed.v1);
