// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	ArticleComments string
	Articles        string
	Bookmarks       string
	Platforms       string
	Profiles        string
}{
	ArticleComments: "article_comments",
	Articles:        "articles",
	Bookmarks:       "bookmarks",
	Platforms:       "platforms",
	Profiles:        "profiles",
}
