// source: favorite/favorite.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.FavoriteArticle', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.FavoriteArticleFolder', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse', null, global);
goog.exportSymbol('proto.checkpicks.favorite.v1.PageInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.displayName = 'proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.repeatedFields_, null);
};
goog.inherits(proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.displayName = 'proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.displayName = 'proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.displayName = 'proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.displayName = 'proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.displayName = 'proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.displayName = 'proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.FavoriteArticle = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.FavoriteArticle, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.FavoriteArticle.displayName = 'proto.checkpicks.favorite.v1.FavoriteArticle';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.FavoriteArticleFolder, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.FavoriteArticleFolder.displayName = 'proto.checkpicks.favorite.v1.FavoriteArticleFolder';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.checkpicks.favorite.v1.PageInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.checkpicks.favorite.v1.PageInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.checkpicks.favorite.v1.PageInfo.displayName = 'proto.checkpicks.favorite.v1.PageInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    keyword: (f = msg.getKeyword()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    cursor: jspb.Message.getFieldWithDefault(msg, 3, ""),
    limit: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest;
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setKeyword(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLimit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKeyword();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLimit();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.protobuf.StringValue keyword = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.getKeyword = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} returns this
*/
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.setKeyword = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.clearKeyword = function() {
  return this.setKeyword(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.hasKeyword = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string cursor = 3;
 * @return {string}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 limit = 4;
 * @return {number}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.getLimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersRequest.prototype.setLimit = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    favoriteArticleFoldersEdgeList: jspb.Message.toObjectList(msg.getFavoriteArticleFoldersEdgeList(),
    proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.toObject, includeInstance),
    pageInfo: (f = msg.getPageInfo()) && proto.checkpicks.favorite.v1.PageInfo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse;
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge;
      reader.readMessage(value,proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.deserializeBinaryFromReader);
      msg.addFavoriteArticleFoldersEdge(value);
      break;
    case 2:
      var value = new proto.checkpicks.favorite.v1.PageInfo;
      reader.readMessage(value,proto.checkpicks.favorite.v1.PageInfo.deserializeBinaryFromReader);
      msg.setPageInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFavoriteArticleFoldersEdgeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.serializeBinaryToWriter
    );
  }
  f = message.getPageInfo();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.checkpicks.favorite.v1.PageInfo.serializeBinaryToWriter
    );
  }
};


/**
 * repeated FavoriteArticleFolderEdge favorite_article_folders_edge = 1;
 * @return {!Array<!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge>}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.getFavoriteArticleFoldersEdgeList = function() {
  return /** @type{!Array<!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge, 1));
};


/**
 * @param {!Array<!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge>} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} returns this
*/
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.setFavoriteArticleFoldersEdgeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge=} opt_value
 * @param {number=} opt_index
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.addFavoriteArticleFoldersEdge = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.clearFavoriteArticleFoldersEdgeList = function() {
  return this.setFavoriteArticleFoldersEdgeList([]);
};


/**
 * optional PageInfo page_info = 2;
 * @return {?proto.checkpicks.favorite.v1.PageInfo}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.getPageInfo = function() {
  return /** @type{?proto.checkpicks.favorite.v1.PageInfo} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.favorite.v1.PageInfo, 2));
};


/**
 * @param {?proto.checkpicks.favorite.v1.PageInfo|undefined} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} returns this
*/
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.setPageInfo = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.clearPageInfo = function() {
  return this.setPageInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFoldersResponse.prototype.hasPageInfo = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    favoriteArticleFolder: (f = msg.getFavoriteArticleFolder()) && proto.checkpicks.favorite.v1.FavoriteArticleFolder.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse;
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.favorite.v1.FavoriteArticleFolder;
      reader.readMessage(value,proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinaryFromReader);
      msg.setFavoriteArticleFolder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFavoriteArticleFolder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.favorite.v1.FavoriteArticleFolder.serializeBinaryToWriter
    );
  }
};


/**
 * optional FavoriteArticleFolder favorite_article_folder = 1;
 * @return {?proto.checkpicks.favorite.v1.FavoriteArticleFolder}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.getFavoriteArticleFolder = function() {
  return /** @type{?proto.checkpicks.favorite.v1.FavoriteArticleFolder} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.favorite.v1.FavoriteArticleFolder, 1));
};


/**
 * @param {?proto.checkpicks.favorite.v1.FavoriteArticleFolder|undefined} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse} returns this
*/
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.setFavoriteArticleFolder = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.clearFavoriteArticleFolder = function() {
  return this.setFavoriteArticleFolder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderResponse.prototype.hasFavoriteArticleFolder = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    articleId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest;
  return proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getArticleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string article_id = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.prototype.getArticleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest} returns this
 */
proto.checkpicks.favorite.v1.GetFavoriteArticleFolderByArticleIdRequest.prototype.setArticleId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    favoriteArticleFolder: (f = msg.getFavoriteArticleFolder()) && proto.checkpicks.favorite.v1.FavoriteArticleFolder.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse;
  return proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.favorite.v1.FavoriteArticleFolder;
      reader.readMessage(value,proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinaryFromReader);
      msg.setFavoriteArticleFolder(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFavoriteArticleFolder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.favorite.v1.FavoriteArticleFolder.serializeBinaryToWriter
    );
  }
};


/**
 * optional FavoriteArticleFolder favorite_article_folder = 1;
 * @return {?proto.checkpicks.favorite.v1.FavoriteArticleFolder}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.getFavoriteArticleFolder = function() {
  return /** @type{?proto.checkpicks.favorite.v1.FavoriteArticleFolder} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.favorite.v1.FavoriteArticleFolder, 1));
};


/**
 * @param {?proto.checkpicks.favorite.v1.FavoriteArticleFolder|undefined} value
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse} returns this
*/
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.setFavoriteArticleFolder = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse} returns this
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.clearFavoriteArticleFolder = function() {
  return this.setFavoriteArticleFolder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderResponse.prototype.hasFavoriteArticleFolder = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest;
  return proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string user_id = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} returns this
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} returns this
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest} returns this
 */
proto.checkpicks.favorite.v1.CreateFavoriteArticleFolderRequest.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.toObject = function(includeInstance, msg) {
  var f, obj = {
    node: (f = msg.getNode()) && proto.checkpicks.favorite.v1.FavoriteArticleFolder.toObject(includeInstance, f),
    cursor: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge;
  return proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.checkpicks.favorite.v1.FavoriteArticleFolder;
      reader.readMessage(value,proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinaryFromReader);
      msg.setNode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCursor(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNode();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.checkpicks.favorite.v1.FavoriteArticleFolder.serializeBinaryToWriter
    );
  }
  f = message.getCursor();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional FavoriteArticleFolder node = 1;
 * @return {?proto.checkpicks.favorite.v1.FavoriteArticleFolder}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.getNode = function() {
  return /** @type{?proto.checkpicks.favorite.v1.FavoriteArticleFolder} */ (
    jspb.Message.getWrapperField(this, proto.checkpicks.favorite.v1.FavoriteArticleFolder, 1));
};


/**
 * @param {?proto.checkpicks.favorite.v1.FavoriteArticleFolder|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.setNode = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.clearNode = function() {
  return this.setNode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.hasNode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string cursor = 2;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.getCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolderEdge.prototype.setCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.FavoriteArticle.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticle} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticle.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    articleId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    platformId: (f = msg.getPlatformId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    favoriteArticleFolderId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 5, ""),
    title: jspb.Message.getFieldWithDefault(msg, 6, ""),
    thumbnailUrl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    articleUrl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    platformFaviconUrl: jspb.Message.getFieldWithDefault(msg, 9, ""),
    publishedAt: (f = msg.getPublishedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    authorName: (f = msg.getAuthorName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    tags: (f = msg.getTags()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    platformName: jspb.Message.getFieldWithDefault(msg, 13, ""),
    platformUrl: jspb.Message.getFieldWithDefault(msg, 14, ""),
    isEng: jspb.Message.getBooleanFieldWithDefault(msg, 15, false),
    isPrivate: jspb.Message.getBooleanFieldWithDefault(msg, 16, false),
    isRead: jspb.Message.getBooleanFieldWithDefault(msg, 17, false),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.FavoriteArticle;
  return proto.checkpicks.favorite.v1.FavoriteArticle.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticle} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleId(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPlatformId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setFavoriteArticleFolderId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setThumbnailUrl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setArticleUrl(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformFaviconUrl(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setPublishedAt(value);
      break;
    case 11:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAuthorName(value);
      break;
    case 12:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setTags(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformName(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlatformUrl(value);
      break;
    case 15:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsEng(value);
      break;
    case 16:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPrivate(value);
      break;
    case 17:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsRead(value);
      break;
    case 18:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 19:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.FavoriteArticle.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticle} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticle.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArticleId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPlatformId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getFavoriteArticleFolderId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getThumbnailUrl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getArticleUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPlatformFaviconUrl();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getPublishedAt();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getAuthorName();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getTags();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPlatformName();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getPlatformUrl();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getIsEng();
  if (f) {
    writer.writeBool(
      15,
      f
    );
  }
  f = message.getIsPrivate();
  if (f) {
    writer.writeBool(
      16,
      f
    );
  }
  f = message.getIsRead();
  if (f) {
    writer.writeBool(
      17,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string article_id = 2;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getArticleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setArticleId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional google.protobuf.StringValue platform_id = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getPlatformId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setPlatformId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearPlatformId = function() {
  return this.setPlatformId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasPlatformId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional string favorite_article_folder_id = 4;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getFavoriteArticleFolderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setFavoriteArticleFolderId = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string user_id = 5;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string title = 6;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string thumbnail_url = 7;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getThumbnailUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setThumbnailUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string article_url = 8;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getArticleUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setArticleUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string platform_favicon_url = 9;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getPlatformFaviconUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setPlatformFaviconUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional google.protobuf.Timestamp published_at = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getPublishedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setPublishedAt = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearPublishedAt = function() {
  return this.setPublishedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasPublishedAt = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.StringValue author_name = 11;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getAuthorName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 11));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setAuthorName = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearAuthorName = function() {
  return this.setAuthorName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasAuthorName = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional google.protobuf.StringValue tags = 12;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getTags = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 12));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setTags = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearTags = function() {
  return this.setTags(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasTags = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional string platform_name = 13;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getPlatformName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setPlatformName = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string platform_url = 14;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getPlatformUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setPlatformUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional bool is_eng = 15;
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getIsEng = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 15, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setIsEng = function(value) {
  return jspb.Message.setProto3BooleanField(this, 15, value);
};


/**
 * optional bool is_private = 16;
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getIsPrivate = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 16, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setIsPrivate = function(value) {
  return jspb.Message.setProto3BooleanField(this, 16, value);
};


/**
 * optional bool is_read = 17;
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getIsRead = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 17, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setIsRead = function(value) {
  return jspb.Message.setProto3BooleanField(this, 17, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 18;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 18));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 19;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 19));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticle} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticle.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 19) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.FavoriteArticleFolder.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    userId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    title: jspb.Message.getFieldWithDefault(msg, 3, ""),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    createdAt: (f = msg.getCreatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedAt: (f = msg.getUpdatedAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.FavoriteArticleFolder;
  return proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedAt(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedAt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.FavoriteArticleFolder.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUserId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCreatedAt();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedAt();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string user_id = 2;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getUserId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setUserId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string title = 3;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp created_at = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getCreatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setCreatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.clearCreatedAt = function() {
  return this.setCreatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.hasCreatedAt = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp updated_at = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.getUpdatedAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
*/
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.setUpdatedAt = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.checkpicks.favorite.v1.FavoriteArticleFolder} returns this
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.clearUpdatedAt = function() {
  return this.setUpdatedAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.FavoriteArticleFolder.prototype.hasUpdatedAt = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.checkpicks.favorite.v1.PageInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.checkpicks.favorite.v1.PageInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.PageInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    endCursor: jspb.Message.getFieldWithDefault(msg, 1, ""),
    hasNextPage: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.checkpicks.favorite.v1.PageInfo}
 */
proto.checkpicks.favorite.v1.PageInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.checkpicks.favorite.v1.PageInfo;
  return proto.checkpicks.favorite.v1.PageInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.checkpicks.favorite.v1.PageInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.checkpicks.favorite.v1.PageInfo}
 */
proto.checkpicks.favorite.v1.PageInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndCursor(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasNextPage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.checkpicks.favorite.v1.PageInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.checkpicks.favorite.v1.PageInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.checkpicks.favorite.v1.PageInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEndCursor();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHasNextPage();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string end_cursor = 1;
 * @return {string}
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.getEndCursor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.checkpicks.favorite.v1.PageInfo} returns this
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.setEndCursor = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool has_next_page = 2;
 * @return {boolean}
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.getHasNextPage = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.checkpicks.favorite.v1.PageInfo} returns this
 */
proto.checkpicks.favorite.v1.PageInfo.prototype.setHasNextPage = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


goog.object.extend(exports, proto.checkpicks.favorite.v1);
