# staging environment
substitutions:
  _IMAGE: 'article-site-and-summary-crawler/latest'
  _JOB_NAME: 'article-site-and-summary-crawler'
  _REGION: 'asia-northeast1'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE','-f', 'batch-service/Dockerfile.article-site-and-summary-crawler', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'deploy'
  - '$_JOB_NAME'
  - '--image'
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE'
  - '--region'
  - '$_REGION'
  # - '--execute-now'
images:
- $_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE