FROM golang:1.22-alpine3.18

RUN apk update && apk add git

WORKDIR /app

COPY ./ ./
# COPY .env go.mod go.sum ./
# COPY ./database ./database
# COPY ./entity ./entity
# COPY ./domain ./domain

RUN go mod download

# Build
RUN go build -o main /app/cmd/trend-article-crawler/main.go

CMD ["/app/main"]