# staging environment
substitutions:
  _IMAGE: 'bookmark-service/latest'
  _SERVICE_NAME: 'bookmark-service-application'
steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE",
        "-f",
        "micro-service/bookmark-service/Dockerfile",
        ".",
      ]
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE"]
  # Deploy container image to Cloud Run
images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_IMAGE