FROM golang:1.23.4-alpine3.21

RUN apk update && apk add git

WORKDIR /app

COPY /micro-service/bookmark-service /app

RUN go mod tidy && \
    go install github.com/air-verse/air@latest &&  \
    go install github.com/volatiletech/sqlboiler/v4@latest && \
    go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest

EXPOSE 3002

CMD ["air", "-c", ".air.toml"]