// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.0.3
//   protoc               v3.20.3
// source: content/category.proto

/* eslint-disable */

export const protobufPackage = "checkpicks.content.v1";

export interface Category {
  id: string;
  name: string;
  type: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | undefined;
}

export const CHECKPICKS_CONTENT_V1_PACKAGE_NAME = "checkpicks.content.v1";
