package usecase

import (
	"time"

	"github.com/YukiOnishi1129/techpicks/batch-service/domain"
)

type seedPlatformFeed struct {
	PlatformName      string
	FeedName          string
	FeedDescription   string
	FeedThumbnail     string
	seedCategoryID    int
	PlatformSiteURL   string
	FeedSiteURL       string
	PlatformType      domain.PlatformType
	FaviconURL        string
	IsEng             bool
	RssURL            string
	APIQueryParam     *string
	TrendPlatformType *domain.TrendPlatformType
	DeletedAt         *time.Time
}

func getSeedPlatformAndFeeds() []seedPlatformFeed {
	deletedAt := time.Now()
	qiitaTrendType := domain.TrendPlatformTypeQiita
	zennTrendType := domain.TrendPlatformTypeZenn
	hatenaTrendType := domain.TrendPlatformTypeHatena
	devCommunityTrendType := domain.TrendPlatformTypeDevCommunity
	hashnodeTrendType := domain.TrendPlatformTypeHashnode

	devComReact := "react"
	devComNextjs := "nextjs"
	devComReactNative := "reactnative"
	devComNodejs := "node"
	devComuTypescript := "typescript"
	devComGo := "go"
	devComAWS := "aws"
	devComGCP := "googlecloud"
	devComDocker := "docker"
	devComTesting := "testing"
	devComGraphQL := "graphql"
	devComFrontendDevelopment := "frontend"
	devComWebDevelopment := "webdev"
	devComAI := "ai"
	devComMachineLearning := "machinelearning"
	devComPrograming := "programming"
	devComDevops := "devops"

	hashnodeReact := "56744723958ef13879b95434"
	hashnodeNextjs := "584879f0c0aaf085e2012086"
	hashnodeReactNative := "56744722958ef13879b94f4d"
	hashnodeNodejs := "56744722958ef13879b94ffb"
	hashnodeTypescript := "56744723958ef13879b954e0"
	hashnodeGo := "56744721958ef13879b94bd0"
	hashnodeAWS := "56744721958ef13879b94bc5"
	hashnodeGCP := "58d4d1fbcfc5bd6596a0a6b5"
	hashnodeDocker := "56744721958ef13879b94b77"
	hashnodeTesting := "56744723958ef13879b9549b"
	hashnodeGraphQL := "56744723958ef13879b9555c"
	hashnodeFrontendDevelopment := "56a399f292921b8f79d3633c"
	hashnodeWebDevelopment := "56744722958ef13879b94f1b"
	hashnodeChatGPT := "638891761e50d717cbfd7b5b"
	hashnodeDeveloper := "56744723958ef13879b952d7"
	hashnodeDevops := "56744723958ef13879b9550d"
	return []seedPlatformFeed{
		{
			PlatformName:      "Qiita",
			FeedName:          "Qiitaのトレンド",
			FeedDescription:   "Qiitaで人気の記事一覧です。毎日5時と17時に更新しています。",
			FeedThumbnail:     "https://cdn.qiita.com/assets/qiita-ogp-3b6fcfdd74755a85107071ffc3155898.png",
			seedCategoryID:    2,
			RssURL:            "https://qiita.com/popular-items/feed.atom",
			PlatformSiteURL:   "https://qiita.com/",
			FeedSiteURL:       "https://qiita.com/trend",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.qiita.com/assets/favicons/public/apple-touch-icon-ec5ba42a24ae923f16825592efdc356f.png",
			IsEng:             false,
			TrendPlatformType: &qiitaTrendType,
		},
		{
			PlatformName:      "Zenn",
			FeedName:          "Zennのトレンド",
			FeedDescription:   "Zennはエンジニアが技術・開発についての知見をシェアする場所です。本の販売や、読者からのバッジの受付により対価を受け取ることができます。",
			FeedThumbnail:     "https://static.zenn.studio/images/logo-only-dark.png",
			seedCategoryID:    2,
			RssURL:            "https://zenn.dev/feed",
			PlatformSiteURL:   "https://zenn.dev/",
			FeedSiteURL:       "https://zenn.dev/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://static.zenn.studio/images/logo-transparent.png",
			IsEng:             false,
			TrendPlatformType: &zennTrendType,
		},
		{
			PlatformName:      "はてなブックマーク",
			FeedName:          "はてなブックマークのテクノロジー",
			FeedDescription:   "はてなブックマークのテクノロジーカテゴリの人気エントリーです。",
			FeedThumbnail:     "https://b.st-hatena.com/d9924dc3407fa42ac2383d043f05c83ecfe06b2b/images/v4/public/apple-touch-icon-precomposed.png",
			seedCategoryID:    2,
			RssURL:            "https://b.hatena.ne.jp/hotentry/it.rss",
			PlatformSiteURL:   "https://b.hatena.ne.jp/",
			FeedSiteURL:       "https://b.hatena.ne.jp/hotentry/it",
			PlatformType:      domain.PlatformTypeSummary,
			FaviconURL:        "https://b.st-hatena.com/9912ec0e0fc8f818cf97c46ebfa93196dc945692/images/v4/public/gh-logo@2x.png",
			IsEng:             false,
			TrendPlatformType: &hatenaTrendType,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Dev Community",
			FeedDescription:   "A constructive and inclusive social network for software developers. With you every step of your journey.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    1,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
		},
		{
			PlatformName:    "A List Apart",
			FeedName:        "A List Apart",
			FeedDescription: "For people who make websites",
			FeedThumbnail:   "https://i0.wp.com/alistapart.com/wp-content/uploads/2019/03/cropped-icon_navigation-laurel-512.jpg?fit=512%2C512&ssl=1",
			seedCategoryID:  1,
			RssURL:          "https://alistapart.com/main/feed/",
			PlatformSiteURL: "https://alistapart.com/",
			FeedSiteURL:     "https://alistapart.com/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://i0.wp.com/alistapart.com/wp-content/uploads/2019/03/cropped-icon_navigation-laurel-512.jpg?fit=32%2C32&ssl=1",

			IsEng:     true,
			DeletedAt: &deletedAt,
		},
		{
			PlatformName:    "David Walsh Blog",
			FeedName:        "David Walsh Blog",
			FeedDescription: "A blog featuring tutorials about JavaScript, HTML5, AJAX, PHP, CSS, WordPress, and everything else development.",
			FeedThumbnail:   "https://davidwalsh.name/wp-content/themes/punky/images/logo.png",
			seedCategoryID:  1,
			RssURL:          "https://davidwalsh.name/feed/atom",
			PlatformSiteURL: "https://davidwalsh.name/",
			FeedSiteURL:     "https://davidwalsh.name/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://davidwalsh.name/wp-content/themes/punky/images/logo.png",

			IsEng: true,
		},
		{
			PlatformName:    "Jack Franklin",
			FeedName:        "Jack Franklin",
			FeedDescription: "Jack Franklin's personal blog about JavaScript and web development.",
			FeedThumbnail:   "https://www.jackfranklin.co.uk/images/favicon/apple-touch-icon.png",
			seedCategoryID:  1,
			RssURL:          "https://www.jackfranklin.co.uk/feed.xml",
			PlatformSiteURL: "https://www.jackfranklin.co.uk/",
			FeedSiteURL:     "https://www.jackfranklin.co.uk/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://www.jackfranklin.co.uk/images/favicon/apple-touch-icon.png",

			IsEng: true,
		},
		{
			PlatformName:    "Stack Overflow",
			FeedName:        "Stack Overflow",
			FeedDescription: "Stack Overflow is the largest, most trusted online community for developers to learn, share their programming knowledge, and build their careers.",
			FeedThumbnail:   "https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon@2.png?v=73d79a89bded",
			seedCategoryID:  1,
			RssURL:          "https://stackoverflow.com/feeds",
			PlatformSiteURL: "https://stackoverflow.com/",
			FeedSiteURL:     "https://stackoverflow.com/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196",
			IsEng:           true,

			DeletedAt: &deletedAt,
		},
		{
			PlatformName:    "free code camp",
			FeedName:        "free code camp",
			FeedDescription: "Browse thousands of programming tutorials written by experts. Learn Web Development, Data Science, DevOps, Security, and get developer career advice.",
			FeedThumbnail:   "https://cdn.freecodecamp.org/platform/universal/fcc_meta_1920X1080-indigo.png",
			seedCategoryID:  1,
			RssURL:          "https://www.freecodecamp.org/news/rss/",
			PlatformSiteURL: "https://www.freecodecamp.org/",
			FeedSiteURL:     "https://www.freecodecamp.org/news/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://cdn.freecodecamp.org/universal/favicons/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "Developer.io",
			FeedName:        "Developer.io",
			FeedDescription: "DevelopersIOは、AWS、iOS/Androidアプリ、ビッグデータ、Alexa等の最新技術情報からリモートワークや働き方に関する記事まで多彩なトピックを紹介するクラスメソッドのオウンドメディアです。",
			FeedThumbnail:   "https://cdn-ssl-devio-img.classmethod.jp/wp-content/uploads/2018/11/eyecatch_developers.io_1200x630.jpeg",
			seedCategoryID:  1,
			RssURL:          "https://dev.classmethod.jp/feed/",
			PlatformSiteURL: "https://dev.classmethod.jp/",
			FeedSiteURL:     "https://dev.classmethod.jp/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://dev.classmethod.jp/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "google japan",
			FeedName:        "google japan",
			FeedDescription: "Google から開発者のみなさま向けの情報をいち早くお届けするブログです。",
			FeedThumbnail:   "https://www.google.co.jp/images/branding/googleg/1x/googleg_standard_color_128dp.png",
			seedCategoryID:  1,
			RssURL:          "https://developers-jp.googleblog.com/atom.xml",
			PlatformSiteURL: "https://developers-jp.googleblog.com/",
			FeedSiteURL:     "https://developers-jp.googleblog.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://developers-jp.googleblog.com/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "楽天　ラクマ事業部",
			FeedName:        "楽天　ラクマ事業部",
			FeedDescription: "楽天ラクマの技術やデザインなど開発情報を紹介します",
			FeedThumbnail:   "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=1200,da=l,ds=s,cc=FFFFFF,of=webp)/assets/images/11573553/original/eaebee03-e376-44b1-bab6-eb67ae93cb04?1671605362",
			seedCategoryID:  1,
			RssURL:          "https://www.wantedly.com/stories/s/rakuma/rss.xml",
			PlatformSiteURL: "https://www.wantedly.com/stories/s/rakuma",
			FeedSiteURL:     "https://www.wantedly.com/stories/s/rakuma",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.wantedly.com//favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "CyberAgent",
			FeedName:        "CyberAgent",
			FeedDescription: "サイバーエージェントのエンジニア・クリエイター・テクニカルクリエイターが執筆する公式ブログです。サイバーエージェントの技術情報を日々発信していきます。",
			FeedThumbnail:   "https://www.cyberagent.co.jp/files/user/img/common/ogp/ogimage.png",
			seedCategoryID:  1,
			RssURL:          "https://developers.cyberagent.co.jp/blog/feed/",
			PlatformSiteURL: "https://developers.cyberagent.co.jp/",
			FeedSiteURL:     "https://developers.cyberagent.co.jp/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://developers.cyberagent.co.jp/blog/wp-content/uploads/2016/09/cropped-ca-32x32.png",

			IsEng: false,
		},
		{
			PlatformName:    "paypay",
			FeedName:        "paypay",
			FeedDescription: "PayPayのエンジニアブログです。",
			FeedThumbnail:   "https://about.paypay.ne.jp/uploads/2022/04/corporate_ogp.png",
			seedCategoryID:  1,
			RssURL:          "https://blog.paypay.ne.jp/category/engineering/feed/",
			PlatformSiteURL: "https://blog.paypay.ne.jp/",
			FeedSiteURL:     "https://blog.paypay.ne.jp/category/engineering/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.paypay.ne.jp/wp-content/uploads/2020/06/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "メルカリ",
			FeedName:        "メルカリ",
			FeedDescription: "「Mercari Engineering」は メルカリのエンジニアに関する情報を、 オープンに公開・共有していくためのサイトです。",
			FeedThumbnail:   "https://engineering.mercari.com//img/ogp/ogp_a.jpg",
			seedCategoryID:  1,
			RssURL:          "https://engineering.mercari.com/blog/feed.xml",
			PlatformSiteURL: "https://engineering.mercari.com/",
			FeedSiteURL:     "https://engineering.mercari.com/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineering.mercari.com/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "NTT",
			FeedName:        "NTT",
			FeedDescription: "NTTコミュニケーションズ (NTT Com) のエンジニアによるブログです。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/622a7a3ca97d84ae19b7c3cee3a987a361f8fb65/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F93285241%2F1621227757889583",
			seedCategoryID:  1,
			RssURL:          "https://engineers.ntt.com/feed",
			PlatformSiteURL: "https://engineers.ntt.com/",
			FeedSiteURL:     "https://engineers.ntt.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineers.ntt.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Qiita (企業)",
			FeedName:        "Qiita (企業)",
			FeedDescription: "Qiitaの企業アカウントの記事一覧です。",
			FeedThumbnail:   "https://cdn.qiita.com/assets/qiita-ogp-3b6fcfdd74755a85107071ffc3155898.png",
			seedCategoryID:  1,
			RssURL:          "https://blog.qiita.com/feed/",
			PlatformSiteURL: "https://blog.qiita.com/",
			FeedSiteURL:     "https://blog.qiita.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.qiita.com/wp-content/uploads/fbrfg/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Cybozu",
			FeedName:        "Cybozu",
			FeedDescription: "サイボウズ株式会社、サイボウズ・ラボ株式会社のエンジニアが提供する技術ブログです。製品やサービスの開発、運用で得た技術情報やエンジニアの活動、採用情報などをお届けします。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/93c02e7921ee4cc02bd26afd9f591bbfacd6253e/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F110495017%2F1514249404572921",
			seedCategoryID:  1,
			RssURL:          "https://blog.cybozu.io/feed",
			PlatformSiteURL: "https://blog.cybozu.io/",
			FeedSiteURL:     "https://blog.cybozu.io/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.cybozu.io/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "mixi",
			FeedName:        "mixi",
			FeedDescription: "株式会社MIXIに所属の開発者による技術知見や開発ノウハウ、カンファレンスレポートなど、開発に関する情報を共有するエンジニア・ブログです。",
			FeedThumbnail:   "https://miro.medium.com/v2/resize:fit:1200/1*lNHpX-0s-NUfCc6OxYFXLQ.png",
			seedCategoryID:  1,
			RssURL:          "https://mixi-developers.mixi.co.jp/feed",
			PlatformSiteURL: "https://mixi-developers.mixi.co.jp/",
			FeedSiteURL:     "https://mixi-developers.mixi.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/v2/resize:fill:256:256/1*lNHpX-0s-NUfCc6OxYFXLQ.png",

			IsEng: false,
		},
		{
			PlatformName:    "GREE",
			FeedName:        "GREE",
			FeedDescription: "GREE株式会社のエンジニアブログです。",
			FeedThumbnail:   "https://labs.gree.jp/blog/wp-content/uploads/2019/03/blog_ogp.jpg",
			seedCategoryID:  1,
			RssURL:          "https://labs.gree.jp/blog/feed/",
			PlatformSiteURL: "https://labs.gree.jp/",
			FeedSiteURL:     "https://labs.gree.jp/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://labs.gree.jp/blog/wp-content/uploads/2015/01/favicon.png",

			IsEng: false,
		},
		{
			PlatformName:    "ZOZO",
			FeedName:        "ZOZO",
			FeedDescription: "ZOZO TECH BLOG",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/1ad4faa3e7226b8dc4d2c7c2c52c197948f09a96/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F51567975%2F1633037350209919",
			seedCategoryID:  1,
			RssURL:          "https://techblog.zozo.com/rss",
			PlatformSiteURL: "https://techblog.zozo.com/",
			FeedSiteURL:     "https://techblog.zozo.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://techblog.zozo.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "DeNA",
			FeedName:        "DeNA",
			FeedDescription: "DeNA Engineering は、DeNAのエンジニアの技術・文化・チーム等を伝えるポータルサイトです。",
			FeedThumbnail:   "https://engineering.dena.com/og.png",
			seedCategoryID:  1,
			RssURL:          "https://engineering.dena.com/index.xml",
			PlatformSiteURL: "https://engineering.dena.com/",
			FeedSiteURL:     "https://engineering.dena.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineering.dena.com/favicon.png",

			IsEng: false,
		},
		{
			PlatformName:    "リクルートテクノロジーズ",
			FeedName:        "リクルートテクノロジーズ",
			FeedDescription: "リクルートテクノロジーズ　メンバーズブログ",
			FeedThumbnail:   "https://blog.recruit.co.jp/rtc/wp-content/themes/pc-rtc-blog.git/library/images/favicon.ico",
			seedCategoryID:  1,
			RssURL:          "https://blog.recruit.co.jp/rtc/feed/",
			PlatformSiteURL: "https://blog.recruit.co.jp/",
			FeedSiteURL:     "https://blog.recruit.co.jp/rtc/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.recruit.co.jp/rtc/wp-content/themes/pc-rtc-blog.git/library/images/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "dwango on GitHub",
			FeedName:        "dwango on GitHub",
			FeedDescription: "ドワンゴ社内の様子や、文化、技術をご紹介します。",
			FeedThumbnail:   "https://dwango.github.io/images/logo.png",
			seedCategoryID:  1,
			RssURL:          "https://dwango.github.io/index.xml",
			PlatformSiteURL: "https://dwango.github.io/",
			FeedSiteURL:     "https://dwango.github.io/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://dwango.github.io/apple-touch-icon-144-precomposed.png",

			IsEng: false,
		},
		{
			PlatformName:    "SanSan",
			FeedName:        "SanSan",
			FeedDescription: "Sansanのものづくりを支えるメンバーの技術やデザイン、プロダクトマネジメントの情報を発信",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/6bfc24bf3dd62203d4c05a87c6891f697842510d/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F157843564%2F1657502198539697",
			seedCategoryID:  1,
			RssURL:          "https://buildersbox.corp-sansan.com/rss",
			PlatformSiteURL: "https://buildersbox.corp-sansan.com/",
			FeedSiteURL:     "https://buildersbox.corp-sansan.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://buildersbox.corp-sansan.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "HRBrain",
			FeedName:        "HRBrain",
			FeedDescription: "HRBrain Blog",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/8a244bed3a65bbbc5fb6044415fa33278a5f2912/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F154374835%2F1554776372268242",
			seedCategoryID:  1,
			RssURL:          "https://times.hrbrain.co.jp/rss",
			PlatformSiteURL: "https://times.hrbrain.co.jp/",
			FeedSiteURL:     "https://times.hrbrain.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://times.hrbrain.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Lineヤフー",
			FeedName:        "Lineヤフー",
			FeedDescription: "LINEヤフー株式会社のサービスを支える、技術・開発文化を発信しています。",
			FeedThumbnail:   "https://techblog.lycorp.co.jp/img/OGP-JP.png",
			seedCategoryID:  1,
			RssURL:          "https://techblog.lycorp.co.jp/ja/feed/index.xml",
			PlatformSiteURL: "https://techblog.lycorp.co.jp/",
			FeedSiteURL:     "https://techblog.lycorp.co.jp/ja",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.lycorp.co.jp/assets/images/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "Sony Music",
			FeedName:        "Sony Music",
			FeedDescription: "Sony Music | Tech Blog",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/fb8117a960272abce71afeaa65d26ca0fbf37540/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F158937347%2F1671616468252707",
			seedCategoryID:  1,
			RssURL:          "https://tech.sme.co.jp/rss",
			PlatformSiteURL: "https://tech.sme.co.jp/",
			FeedSiteURL:     "https://tech.sme.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.sme.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "IBM",
			FeedName:        "IBM",
			FeedDescription: "IBM の製品・ソリューション・サービスに関連する最新情報をお届けします。",
			FeedThumbnail:   "https://1.www.s81c.com/common/images/ibm-leadspace-1200x627.jpg",
			seedCategoryID:  1,
			RssURL:          "https://www.ibm.com/blogs/solutions/jp-ja/feed/atom/",
			PlatformSiteURL: "https://www.ibm.com/",
			FeedSiteURL:     "https://www.ibm.com/blogs/solutions/jp-ja/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.ibm.com/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "カミナシ",
			FeedName:        "カミナシ",
			FeedDescription: "株式会社カミナシのエンジニアが色々書くブログです",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/b0e74e9906adf65759a488c0a784d12c3175c45b/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F157288706%2F1669774223105431",
			seedCategoryID:  1,
			RssURL:          "https://kaminashi-developer.hatenablog.jp/rss",
			PlatformSiteURL: "https://kaminashi-developer.hatenablog.jp/",
			FeedSiteURL:     "https://kaminashi-developer.hatenablog.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://kaminashi-developer.hatenablog.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "ANDPAD",
			FeedName:        "ANDPAD",
			FeedDescription: "ANDPAD の開発部からのお知らせやエンジニアリングに関する話題を発信するTech Blog です。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/eb26db6069074009224581f096a5035c92a009eb/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F154574578%2F1589786066779907",
			seedCategoryID:  1,
			RssURL:          "https://tech.andpad.co.jp/rss",
			PlatformSiteURL: "https://tech.andpad.co.jp/",
			FeedSiteURL:     "https://tech.andpad.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.andpad.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "gaudiy",
			FeedName:        "gaudiy",
			FeedDescription: "Gaudiyの技術、開発組織、カルチャーについてお伝えするブログです",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/8db2da894b46422604c66082b5654897da03e32a/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F156807968%2F1697054382687926",
			seedCategoryID:  1,
			RssURL:          "https://techblog.gaudiy.com/rss",
			PlatformSiteURL: "https://techblog.gaudiy.com/",
			FeedSiteURL:     "https://techblog.gaudiy.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://techblog.gaudiy.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "aws amazon web services",
			FeedName:        "aws amazon web services",
			FeedDescription: "Amazon Web Services ブログ",
			FeedThumbnail:   "https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_179x109.png",
			seedCategoryID:  1,
			RssURL:          "https://aws.amazon.com/jp/blogs/news/feed/",
			PlatformSiteURL: "https://aws.amazon.com/",
			FeedSiteURL:     "https://aws.amazon.com/jp/blogs/news/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://a0.awsstatic.com/main/images/site/fav/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "aws startup",
			FeedName:        "aws startup",
			FeedDescription: "AWS Startup ブログ",
			FeedThumbnail:   "https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_179x109.png",
			seedCategoryID:  1,
			RssURL:          "https://aws.amazon.com/jp/blogs/startup/feed/",
			PlatformSiteURL: "https://aws.amazon.com/",
			FeedSiteURL:     "https://aws.amazon.com/jp/blogs/startup/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://a0.awsstatic.com/main/images/site/fav/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "LayerX",
			FeedName:        "LayerX",
			FeedDescription: "LayerX の エンジニアブログです。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/1e24ea6e97b140a779a78a6f77a72d6a6e996ffc/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F29440%2F1690850324393740",
			seedCategoryID:  1,
			RssURL:          "https://tech.layerx.co.jp/rss",
			PlatformSiteURL: "https://tech.layerx.co.jp/",
			FeedSiteURL:     "https://tech.layerx.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.layerx.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "UPSIDER",
			FeedName:        "UPSIDER",
			FeedDescription: "UPSIDER Techblog",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/182788fbc5de20fd367b9813eac80a93f431f332/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F158846028%2F1660112173520838",
			seedCategoryID:  1,
			RssURL:          "https://tech.up-sider.com/rss",
			PlatformSiteURL: "https://tech.up-sider.com/",
			FeedSiteURL:     "https://tech.up-sider.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.up-sider.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "CADDI",
			FeedName:        "CADDI",
			FeedDescription: "キャディ株式会社のTechブログです",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/9f4be164cdc32334865881b7f8124bdf6a5a436c/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F159376513%2F1709270017315899",
			seedCategoryID:  1,
			RssURL:          "https://caddi.tech/rss",
			PlatformSiteURL: "https://caddi.tech/",
			FeedSiteURL:     "https://caddi.tech/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://caddi.tech/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "UZABASE",
			FeedName:        "UZABASE",
			FeedDescription: "SPEEDA, NewsPicks, FORCASなどを開発するユーザベースのエンジニア採用サイト",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/44e2f1cd375b3094801dc574150c8eb832da6e99/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F157994487%2F1663747659382551",
			seedCategoryID:  1,
			RssURL:          "https://tech.uzabase.com/rss/category/Blog",
			PlatformSiteURL: "https://tech.uzabase.com/",
			FeedSiteURL:     "https://tech.uzabase.com/archive/category/Blog",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.uzabase.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "BASE",
			FeedName:        "BASE",
			FeedDescription: "ネットショップ作成サービス「BASE ( https://thebase.in )」、ショッピングアプリ「BASE ( https://thebase.in/sp )」のプロダクトチームによるブログです。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/dc2fba68e09e63196065a56236b211a796b9e343/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F153078222%2F1614340287711564",
			seedCategoryID:  1,
			RssURL:          "https://devblog.thebase.in/rss",
			PlatformSiteURL: "https://devblog.thebase.in/",
			FeedSiteURL:     "https://devblog.thebase.in/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://devblog.thebase.in/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "タイミー",
			FeedName:        "タイミー",
			FeedDescription: "タイミー開発者ブログ",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/184a7bf05f5c811949943e163ca4c5ff1cbf64df/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F155704439%2F158718819466986",
			seedCategoryID:  1,
			RssURL:          "https://tech.timee.co.jp/rss",

			PlatformSiteURL: "https://tech.timee.co.jp/",
			FeedSiteURL:     "https://tech.timee.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.timee.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "はてな開発者ブログ",
			FeedName:        "はてな開発者ブログ",
			FeedDescription: "はてな開発者ブログ",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/3b8ea1810a825c4fd905888379c854f7697e055b/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F70728728%2F1633074720678305",
			seedCategoryID:  1,
			RssURL:          "https://developer.hatenastaff.com/rss",

			PlatformSiteURL: "https://developer.hatenastaff.com/",
			FeedSiteURL:     "https://developer.hatenastaff.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://developer.hatenastaff.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Money Forward",
			FeedName:        "Money Forward",
			FeedDescription: "株式会社マネーフォワード公式開発者向けブログです。技術や開発手法、イベント登壇などを発信します。サービスに関するご質問は、各サービス窓口までご連絡ください。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/3d3b3c184e068231cc1cb8402f39278971367731/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F158909383%2F1667877695816130",
			seedCategoryID:  1,
			RssURL:          "https://moneyforward-dev.jp/rss",

			PlatformSiteURL: "https://moneyforward-dev.jp/",
			FeedSiteURL:     "https://moneyforward-dev.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://moneyforward-dev.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "pixiv",
			FeedName:        "pixiv",
			FeedDescription: "ピクシブの日常を伝えるオウンドメディアです。ピクシブのものづくりや、ピクシブで働く雰囲気がわかります。",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/8dff70a8ddbba20681923393bbd3869338a78f6d/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F155500129%2F1577143393788739",
			seedCategoryID:  1,
			RssURL:          "https://inside.pixiv.blog/rss",

			PlatformSiteURL: "https://inside.pixiv.blog/",
			FeedSiteURL:     "https://inside.pixiv.blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://inside.pixiv.blog/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "speee",
			FeedName:        "speee",
			FeedDescription: "Speee開発陣による技術情報発信ブログです。 メディア開発・運用、スマートフォンアプリ開発、Webマーケティング、アドテクなどで培った技術ノウハウを発信していきます！",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/82b2744413fef2d9821bdfd7b39cfb5b47fac095/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F115761273%2F1514195728888882",
			seedCategoryID:  1,
			RssURL:          "https://tech.speee.jp/rss",

			PlatformSiteURL: "https://tech.speee.jp/",
			FeedSiteURL:     "https://tech.speee.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.speee.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Gunosy",
			FeedName:        "Gunosy",
			FeedDescription: "Gunosy Tech Blogは株式会社Gunosyのエンジニアが知見を共有する技術ブログです。",
			FeedThumbnail:   "https://gunosy.co.jp/img/Gunosy_ogp.png",
			seedCategoryID:  1,
			RssURL:          "https://tech.gunosy.io/rss",

			PlatformSiteURL: "https://tech.gunosy.io/",
			FeedSiteURL:     "https://tech.gunosy.io/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.gunosy.io/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "クックパッド",
			FeedName:        "クックパッド",
			FeedDescription: "クックパッド開発者ブログ",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/17bd9c23f05610c2383f43fe589ff7e0f9383f62/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F6628210%2F1516165995781773",
			seedCategoryID:  1,
			RssURL:          "https://techlife.cookpad.com/rss",

			PlatformSiteURL: "https://techlife.cookpad.com/",
			FeedSiteURL:     "https://techlife.cookpad.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://techlife.cookpad.com/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "wantedly",
			FeedName:        "wantedly",
			FeedDescription: "Wantedlyのエンジニアによる、テックブログです。開発者向け技術情報を中心に発信しています。「シゴトでココロオドル人をふやす」というミッションを掲げ、ビジネスSNS Wantedly （ウォンテッドリー）を展開しています。",
			FeedThumbnail:   "https://d2v9k5u4v94ulw.cloudfront.net/small_light(dw=1200,da=l,ds=s,cc=FFFFFF,of=webp)/assets/images/17615726/original/781259bb-6cdc-4d93-8d2f-75291ed1f303?1713229870",
			seedCategoryID:  1,
			RssURL:          "https://www.wantedly.com/stories/s/wantedly_engineers/rss.xml",

			PlatformSiteURL: "https://www.wantedly.com/",
			FeedSiteURL:     "https://www.wantedly.com/stories/s/wantedly_engineers",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.wantedly.com//favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "ABEJA",
			FeedName:        "ABEJA",
			FeedDescription: "中の人の興味のある情報を発信していきます",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/806b22fb519f9f2b74577ceae826ae03c8e941dd/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F103165225%2F1519263533220245",
			seedCategoryID:  1,
			RssURL:          "https://tech-blog.abeja.asia/rss",

			PlatformSiteURL: "https://tech-blog.abeja.asia/",
			FeedSiteURL:     "https://tech-blog.abeja.asia/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech-blog.abeja.asia/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "AppBrew",
			FeedName:        "AppBrew",
			FeedDescription: "株式会社AppBrewの技術に関するブログ",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/dd0d8f369de16882ea9c6c43c8d7072a13c86761/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F150280505%2F1673597439835304",
			seedCategoryID:  1,
			RssURL:          "https://tech.appbrew.io/rss",

			PlatformSiteURL: "https://tech.appbrew.io/",
			FeedSiteURL:     "https://tech.appbrew.io/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.appbrew.io/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "エウレカ",
			FeedName:        "エウレカ",
			FeedDescription: "Learn about Eureka’s engineering efforts, product developments and more.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*4nQvYibd3aHYOp1xrvmfMQ.png",
			seedCategoryID:  1,
			RssURL:          "https://medium.com/feed/eureka-engineering",

			PlatformSiteURL: "https://medium.com/eureka-engineering/",
			FeedSiteURL:     "https://medium.com/eureka-engineering/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: false,
		},
		{
			PlatformName:    "Airbnb",
			FeedName:        "Airbnb",
			FeedDescription: "Creative engineers and data scientists building a world where you can belong anywhere. http://airbnb.io.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*MlNQKg-sieBGW5prWoe9HQ.jpeg",
			seedCategoryID:  1,
			RssURL:          "https://medium.com/feed/airbnb-engineering",

			PlatformSiteURL: "https://medium.com/airbnb-engineering/",
			FeedSiteURL:     "https://medium.com/airbnb-engineering/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: true,
		},
		{
			PlatformName:    "Atlassian",
			FeedName:        "Atlassian",
			FeedDescription: "Atlassian Developer Blog",
			FeedThumbnail:   "https://blog.developer.atlassian.com/wp-content/uploads/2019/02/cropped-Atlassian-Developer@2x-blue-rgb-270x270.png",
			seedCategoryID:  1,
			RssURL:          "https://blog.developer.atlassian.com/feed/",

			PlatformSiteURL: "https://blog.developer.atlassian.com/",
			FeedSiteURL:     "https://blog.developer.atlassian.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.developer.atlassian.com/wp-content/uploads/2019/02/cropped-Atlassian-Developer@2x-blue-rgb-32x32.png",

			IsEng: true,
		},
		{
			PlatformName:    "Docker",
			FeedName:        "Docker",
			FeedDescription: "Read our blog to find the latest Docker updates, news, technical breakdowns, and lifestyle content.",
			FeedThumbnail:   "https://www.docker.com/wp-content/uploads/2022/12/Docker-Temporary-Image-Social-Thumbnail-1200x630-1.png",
			seedCategoryID:  1,
			RssURL:          "https://www.docker.com/feed/",

			PlatformSiteURL: "https://www.docker.com/",
			FeedSiteURL:     "https://www.docker.com/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.docker.com/wp-content/uploads/2024/02/cropped-docker-logo-favicon-32x32.png",

			IsEng: true,
		},
		{
			PlatformName:    "Meta",
			FeedName:        "Meta",
			FeedDescription: "Engineering at Meta Blog",
			FeedThumbnail:   "https://engineering.fb.com/wp-content/themes/code-fb-com/img/default_feature.jpg",
			seedCategoryID:  1,
			RssURL:          "https://engineering.fb.com/feed/",

			PlatformSiteURL: "https://engineering.fb.com/",
			FeedSiteURL:     "https://engineering.fb.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineering.fb.com/wp-content/themes/code-fb-com/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "GitHub",
			FeedName:        "GitHub",
			FeedDescription: "See what the GitHub Engineering team is up to—from building features to solving the nagging challenges teams face as they grow.",
			FeedThumbnail:   "https://github.blog/wp-content/uploads/2019/03/engineering-social.png?fit=1201%2C630",
			seedCategoryID:  1,
			RssURL:          "https://github.blog/category/engineering/feed/",

			PlatformSiteURL: "https://github.blog/",
			FeedSiteURL:     "https://github.blog/category/engineering/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://github.githubassets.com/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "Google",
			FeedName:        "Google",
			FeedDescription: "Explore the Google for Developers Blog which provides insights and the latest news about our AI, Cloud, Mobile and Web app development announcements.",
			FeedThumbnail:   "https://www.gstatic.com/dgc_blog/images/meta.png",
			seedCategoryID:  1,
			RssURL:          "https://www.blogger.com/feeds/596098824972435195/posts/default",

			PlatformSiteURL: "https://developers.googleblog.com/",
			FeedSiteURL:     "https://developers.googleblog.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://developers.googleblog.com/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "Instagram",
			FeedName:        "Instagram",
			FeedDescription: "Stories from the people who build @Instagram.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*CPgwLHR6jno_tOmF0--7eg.jpeg",
			seedCategoryID:  1,
			RssURL:          "https://instagram-engineering.com/feed",

			PlatformSiteURL: "https://instagram-engineering.com/",
			FeedSiteURL:     "https://instagram-engineering.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: true,
		},
		{
			PlatformName:    "Netflix",
			FeedName:        "Netflix",
			FeedDescription: "Learn about Netflix’s world class engineering efforts, company culture, product developments and more.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*ty4NvNrGg4ReETxqU2N3Og.png",
			seedCategoryID:  1,
			RssURL:          "https://netflixtechblog.com/feed",

			PlatformSiteURL: "https://netflixtechblog.com/",
			FeedSiteURL:     "https://netflixtechblog.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: true,
		},
		{
			PlatformName:    "PayPal",
			FeedName:        "PayPal",
			FeedDescription: "Join our technology team at careers.pypl.com.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*7gvURHIXUXK4Y-aSaqJONQ.png",
			seedCategoryID:  1,
			RssURL:          "https://medium.com/feed/paypal-tech",

			PlatformSiteURL: "https://medium.com/paypal-tech/",
			FeedSiteURL:     "https://medium.com/paypal-tech/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: true,
		},
		{
			PlatformName:    "Salesforce",
			FeedName:        "Salesforce",
			FeedDescription: "Read the latest articles on the Salesforce Engineering blog. Go behind the cloud with Salesforce Engineers.",
			FeedThumbnail:   "https://engineering.salesforce.com/wp-content/uploads/2022/06/See-whats-happening-beyond-the-cloud.png",
			seedCategoryID:  1,
			RssURL:          "https://engineering.salesforce.com/feed/",

			PlatformSiteURL: "https://engineering.salesforce.com/",
			FeedSiteURL:     "https://engineering.salesforce.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineering.salesforce.com/wp-content/uploads/2022/05/salesforce-icon.png?w=32",

			IsEng: true,
		},
		{
			PlatformName:    "Zoom",
			FeedName:        "Zoom",
			FeedDescription: "All the ways you can join, build, and create on the Zoom Developer platform.",
			FeedThumbnail:   "https://cdn-images-1.medium.com/max/1200/1*RKOMNTxW2hAU9UzlW6OLHg.png",
			seedCategoryID:  1,
			RssURL:          "https://medium.com/feed/zoom-developer-blog",

			PlatformSiteURL: "https://medium.com/zoom-developer-blog/",
			FeedSiteURL:     "https://medium.com/zoom-developer-blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://miro.medium.com/1*m-R_BkNf1Qjr1YbyOIJY2w.png",

			IsEng: true,
		},
		{
			PlatformName:    "Asana",
			FeedName:        "Asana",
			FeedDescription: "Are you interested in learning more about working on Asana's engineering team or the work they do? Read the Asana engineering blog.",
			FeedThumbnail:   "https://blog.asana.com/wp-content/post-images/Blog-home-metadata-2021-3.png",
			seedCategoryID:  1,
			RssURL:          "https://blog.asana.com/category/eng/feed/",

			PlatformSiteURL: "https://blog.asana.com/category/eng/",
			FeedSiteURL:     "https://blog.asana.com/category/eng/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://d1gwm4cf8hecp4.cloudfront.net/images/favicons/apple-touch-icon-57x57.png",

			IsEng: true,
		},
		{
			PlatformName:    "mercari",
			FeedName:        "mercari",
			FeedDescription: "Mercari Engineering Portal",
			FeedThumbnail:   "https://engineering.mercari.com/favicons/android-chrome-512x512.png",
			seedCategoryID:  1,
			RssURL:          "https://engineering.mercari.com/en/blog/feed.xml",

			PlatformSiteURL: "https://engineering.mercari.com/en/blog/",
			FeedSiteURL:     "https://engineering.mercari.com/en/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://engineering.mercari.com/favicon.ico/",

			IsEng: true,
		},
		{
			PlatformName:    "ROUTE 06",
			FeedName:        "ROUTE 06",
			FeedDescription: "ROUTE06 Tech Blog",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/5de6581bb84aa8f4c571bf21096175fdc464a4cd/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F159033270%2F1677230915741336",
			seedCategoryID:  1,
			RssURL:          "https://tech.route06.co.jp/feed",

			PlatformSiteURL: "https://tech.route06.co.jp/",
			FeedSiteURL:     "https://tech.route06.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.route06.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "スタディサプリ",
			FeedName:        "スタディサプリ",
			FeedDescription: "株式会社リクルートが開発するスタディサプリのプロダクトチームのブログです",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/0d821cf3fd1372237caf085d5dc080ef49fb6670/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F125757465%2F168916493131424",
			seedCategoryID:  1,
			RssURL:          "https://blog.studysapuri.jp/rss",

			PlatformSiteURL: "https://blog.studysapuri.jp/",
			FeedSiteURL:     "https://blog.studysapuri.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.studysapuri.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Menthas",
			FeedName:        "Menthas",
			FeedDescription: "Menthas(メンタス)は、プログラマ向けニュースキュレーションサービスです。フロントエンドからインフラ、機械学習やVRといった様々なジャンルの最新情報を提供します。",
			FeedThumbnail:   "https://menthas.com/apple-touch-icon.png",
			seedCategoryID:  2,
			RssURL:          "https://menthas.com/all/rss",

			PlatformSiteURL: "https://menthas.com/",
			FeedSiteURL:     "https://menthas.com/",
			PlatformType:    domain.PlatformTypeSummary,
			FaviconURL:      "https://menthas.com/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Menthas",
			FeedName:        "Menthas programing",
			FeedDescription: "menthas programing news | プログラミングに関する最新情報をお届けします。",
			FeedThumbnail:   "https://menthas.com/apple-touch-icon.png",
			seedCategoryID:  4,
			RssURL:          "https://menthas.com/programming/rss",

			PlatformSiteURL: "https://menthas.com/",
			FeedSiteURL:     "https://menthas.com/programming/",
			PlatformType:    domain.PlatformTypeSummary,
			FaviconURL:      "https://menthas.com/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Menthas",
			FeedName:        "Menthas javascript",
			FeedDescription: "menthas javascript news | JavaScriptに関する最新情報をお届けします。",
			FeedThumbnail:   "https://menthas.com/apple-touch-icon.png",
			seedCategoryID:  5,
			RssURL:          "https://menthas.com/javascript/rss",

			PlatformSiteURL: "https://menthas.com/",
			FeedSiteURL:     "https://menthas.com/javascript/",
			PlatformType:    domain.PlatformTypeSummary,
			FaviconURL:      "https://menthas.com/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Menthas",
			FeedName:        "Menthas infrastructure",
			FeedDescription: "menthas infrastructure news | インフラに関する最新情報をお届けします。",
			FeedThumbnail:   "https://menthas.com/apple-touch-icon.png",
			seedCategoryID:  25,
			RssURL:          "https://menthas.com/infrastructure/rss",

			PlatformSiteURL: "https://menthas.com/",
			FeedSiteURL:     "https://menthas.com/infrastructure/",
			PlatformType:    domain.PlatformTypeSummary,
			FaviconURL:      "https://menthas.com/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn React",
			FeedDescription: "Reactの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/489b9436a3.png",
			seedCategoryID:  18,
			RssURL:          "https://zenn.dev/topics/react/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/react/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Next.js",
			FeedDescription: "Next.jsの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/d87ff27d89.png",
			seedCategoryID:  18,
			RssURL:          "https://zenn.dev/topics/nextjs/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/nextjs/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn React Native",
			FeedDescription: "React Nativeの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/658126d68f.png",
			seedCategoryID:  26,
			RssURL:          "https://zenn.dev/topics/reactnative/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/reactnative/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn JavaScript",
			FeedDescription: "JavaScriptの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/64acd76870.png",
			seedCategoryID:  5,
			RssURL:          "https://zenn.dev/topics/javascript/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/javascript/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn TypeScript",
			FeedDescription: "TypeScriptの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/f13e758fdb.png",
			seedCategoryID:  6,
			RssURL:          "https://zenn.dev/topics/typescript/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/typescript/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Node.js",
			FeedDescription: "Node.jsの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/54d1e3ddea.png",
			seedCategoryID:  22,
			RssURL:          "https://zenn.dev/topics/nodejs/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/nodejs/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Golang",
			FeedDescription: "Golangの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/8b677725c8.png",
			seedCategoryID:  9,
			RssURL:          "https://zenn.dev/topics/go/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/go/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn AWS",
			FeedDescription: "AWSの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/dc1922748b.png",
			seedCategoryID:  28,
			RssURL:          "https://zenn.dev/topics/aws/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/aws/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn GCP",
			FeedDescription: "GCPの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/90aad273f0.png",
			seedCategoryID:  29,
			RssURL:          "https://zenn.dev/topics/gcp/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/gcp/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Docker",
			FeedDescription: "Dockerの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/01c7f20365.png",
			seedCategoryID:  31,
			RssURL:          "https://zenn.dev/topics/docker/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/docker/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn GraphQL",
			FeedDescription: "GraphQLの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/d3a7f336d2.png",
			seedCategoryID:  36,
			RssURL:          "https://zenn.dev/topics/graphql/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/graphql/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn GitHub",
			FeedDescription: "GitHubの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/3a8fd1cede.png",
			seedCategoryID:  37,
			RssURL:          "https://zenn.dev/topics/github/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/github/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn GitHub Actions",
			FeedDescription: "GitHub Actionsの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/da1b8cf8f6.jpeg",
			seedCategoryID:  40,
			RssURL:          "https://zenn.dev/topics/githubactions/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/githubactions/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn ChatGPT",
			FeedDescription: "ChatGPTの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/2bb6923651.png",
			seedCategoryID:  41,
			RssURL:          "https://zenn.dev/topics/chatgpt/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/chatgpt/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn 個人開発",
			FeedDescription: "個人開発の記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/604d5b83b5.jpeg",
			seedCategoryID:  42,
			RssURL:          "https://zenn.dev/topics/個人開発/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/個人開発/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Frontend",
			FeedDescription: "フロントエンドの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/d766db09a2.jpeg",
			seedCategoryID:  43,
			RssURL:          "https://zenn.dev/topics/frontend/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/frontend/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},
		{
			PlatformName:    "Zenn",
			FeedName:        "Zenn Test",
			FeedDescription: "テストの記事一覧 | Zenn",
			FeedThumbnail:   "https://storage.googleapis.com/zenn-user-upload/topics/902109da93.jpeg",
			seedCategoryID:  44,
			RssURL:          "https://zenn.dev/topics/test/feed",

			PlatformSiteURL: "https://zenn.dev/",
			FeedSiteURL:     "https://zenn.dev/topics/test/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://static.zenn.studio/images/logo-transparent.png",

			IsEng: false,
		},

		{
			PlatformName:    "LogRocket",
			FeedName:        "LogRocket",
			FeedDescription: "Resources to Help Product Teams Ship Amazing Digital Experiences",
			FeedThumbnail:   "https://blog.logrocket.com/wp-content/uploads/2019/05/logrocket-blog.jpg",
			seedCategoryID:  1,
			RssURL:          "https://blog.logrocket.com/feed/",

			PlatformSiteURL: "https://blog.logrocket.com/",
			FeedSiteURL:     "https://blog.logrocket.com/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.logrocket.com/wp-content/uploads/2019/06/cropped-cropped-favicon-196x196.png?w=192",

			IsEng: true,
		},
		{
			PlatformName:    "フューチャー技術ブログ",
			FeedName:        "フューチャー技術ブログ",
			FeedDescription: "フューチャーの開発者による公式技術ブログです。業務で利用している技術を幅広く紹介します。",
			FeedThumbnail:   "https://future-architect.github.io/ogp_techblog.jpg",
			seedCategoryID:  1,
			RssURL:          "https://future-architect.github.io/atom.xml",

			PlatformSiteURL: "https://future-architect.github.io/",
			FeedSiteURL:     "https://future-architect.github.io/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://future-architect.github.io/favicon.ico",

			IsEng: false,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal",
			FeedDescription: "A hub for in-depth business, design, and technology tutorials and trends. Our research and publications are authored by expert professionals from the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/5791128/og_image/optimized/og-image-blog__1_-abdd426549359282c6f486ee85a2ee54.png",
			seedCategoryID:  1,
			RssURL:          "https://www.toptal.com/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal engineering",
			FeedDescription: "Toptal Engineering Blog: Expert Insights and Best Practices. The Toptal Engineering Blog is a hub for in-depth development tutorials and new technology announcements created by professional software engineers in the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/7986388/og_image/optimized/og-image-blog-eng-6e8019eb50758008cce1bad8ec85a209.png",
			seedCategoryID:  47,
			RssURL:          "https://www.toptal.com/developers/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/developers/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal design",
			FeedDescription: "Toptal Design Blog: Expert Insights and Best Practices. The Toptal Design Blog is a hub for in-depth design tutorials and new technology announcements created by professional designers in the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/8158028/og_image/optimized/og-image-blog-des-9882e3585454bca06bd731e0af338cad.png",
			seedCategoryID:  48,
			RssURL:          "https://www.toptal.com/designers/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/designers/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal finance",
			FeedDescription: "Toptal Finance Blog: Expert Insights and Best Practices. The Toptal Finance Blog is a hub for in-depth finance tutorials and new technology announcements created by professional finance experts in the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/5784432/og_image/optimized/og-image-blog-fin-471dbaa1d493889fc7084cbca025a472.png",
			seedCategoryID:  49,
			RssURL:          "https://www.toptal.com/finance/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/finance/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal project",
			FeedDescription: "Toptal Project Management Blog: Expert Insights and Best Practices. The Toptal Project Management Blog is a hub for in-depth project management tutorials and new technology announcements created by professional project managers in the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/5784441/og_image/optimized/og-image-blog-pm-fb78e752065de4d23ae27c6a3b4c01a4.png",
			seedCategoryID:  50,
			RssURL:          "https://www.toptal.com/project-managers/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/project-managers/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "toptal",
			FeedName:        "toptal product",
			FeedDescription: "Toptal Product Management Blog: Expert Insights and Best Practices. The Toptal Product Management Blog is a hub for in-depth product management tutorials and new technology announcements created by professional product managers in the Toptal network.",
			FeedThumbnail:   "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/5866178/og_image/optimized/og-image-blog-pdm-bc89810d98a4299f54c3fa67d8d44cbd.png",
			seedCategoryID:  51,
			RssURL:          "https://www.toptal.com/product-managers/blog.rss",

			PlatformSiteURL: "https://www.toptal.com/",
			FeedSiteURL:     "https://www.toptal.com/product-managers/blog/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://frontier-assets.toptal.com/1fafc84237661afb2281.png",

			IsEng: true,
		},
		{
			PlatformName:    "Findy",
			FeedName:        "Findy",
			FeedDescription: "Findy Tech Blog",
			FeedThumbnail:   "https://cdn.image.st-hatena.com/image/scale/6d855d5698586228d443149665e3097dcfc30c8e/backend=imager;enlarge=0;height=1000;version=1;width=1200/https%3A%2F%2Fcdn.user.blog.st-hatena.com%2Fdefault_entry_og_image%2F94582793%2F1710244091931727",
			seedCategoryID:  1,
			RssURL:          "https://tech.findy.co.jp/rss",

			PlatformSiteURL: "https://tech.findy.co.jp/",
			FeedSiteURL:     "https://tech.findy.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.findy.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "Hacker News",
			FeedName:        "Hacker News",
			FeedDescription: "Hacker News is a social news website focusing on computer science and entrepreneurship. It is run by Paul Graham's investment fund and startup incubator, Y Combinator.",
			FeedThumbnail:   "https://news.ycombinator.com/y18.svg",
			seedCategoryID:  2,
			RssURL:          "https://news.ycombinator.com/rss",

			PlatformSiteURL: "https://news.ycombinator.com/",
			FeedSiteURL:     "https://news.ycombinator.com/",
			PlatformType:    domain.PlatformTypeSummary,
			FaviconURL:      "https://news.ycombinator.com/y18.svg",

			IsEng: true,
		},
		{
			PlatformName:    "Techmeme",
			FeedName:        "Techmeme",
			FeedDescription: "The essential tech news of the moment. Technology's news site of record. Not for dummies.",
			FeedThumbnail:   "https://www.techmeme.com/m/config/tech/iicon.gif",
			seedCategoryID:  2,
			RssURL:          "https://www.techmeme.com/feed.xml",

			PlatformSiteURL: "https://techmeme.com/",
			FeedSiteURL:     "https://techmeme.com/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://techmeme.com/img/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "WIRED",
			FeedName:        "WIRED",
			FeedDescription: "We bring you the future as it happens. From the latest in science and technology to the big stories in business and culture, we've got you covered.",
			FeedThumbnail:   "https://media.wired.com/photos/615e2b8ce78a8cd913bbaa76/16:9/w_1280,c_limit/wired_bug.jpg",
			seedCategoryID:  2,
			RssURL:          "https://www.wired.com/feed/rss",

			PlatformSiteURL: "https://www.wired.com/",
			FeedSiteURL:     "https://www.wired.com/",
			PlatformType:    domain.PlatformTypeSite,
			FaviconURL:      "https://www.wired.com/favicon.ico",

			IsEng: true,
		},
		{
			PlatformName:    "SmartHR",
			FeedName:        "SmartHR",
			FeedDescription: "SmartHR 開発者ブログ",
			FeedThumbnail:   "https://cdn.user.blog.st-hatena.com/default_entry_og_image/51907959/1518583134492221",
			seedCategoryID:  1,
			RssURL:          "https://tech.smarthr.jp/rss",

			PlatformSiteURL: "https://tech.smarthr.jp/",
			FeedSiteURL:     "https://tech.smarthr.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://tech.smarthr.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "G-gen",
			FeedName:        "G-gen",
			FeedDescription: "Google Cloud(旧称GCP)の情報発信を行う技術ブログ",
			FeedThumbnail:   "https://cdn.user.blog.st-hatena.com/default_entry_og_image/158491034/1633396648613392",
			seedCategoryID:  1,
			RssURL:          "https://blog.g-gen.co.jp/rss",

			PlatformSiteURL: "https://blog.g-gen.co.jp/",
			FeedSiteURL:     "https://blog.g-gen.co.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://blog.g-gen.co.jp/icon/favicon",

			IsEng: false,
		},
		{
			PlatformName:    "さくらインターネット",
			FeedName:        "さくらのナレッジ",
			FeedDescription: "さくらのナレッジは、さくらインターネットが運営する技術情報メディアです。サーバー運用やプログラミング、ネットワーク、セキュリティなど、ITエンジニアに役立つ情報をお届けします。",
			FeedThumbnail:   "https://knowledge.sakura.ad.jp/wp-content/themes/sakunare/assets/images/common/ogp.png",
			seedCategoryID:  1,
			RssURL:          "https://knowledge.sakura.ad.jp/feed/",

			PlatformSiteURL: "https://knowledge.sakura.ad.jp/",
			FeedSiteURL:     "https://knowledge.sakura.ad.jp/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://www.sakura.ad.jp/resource/favicon/sakura_logo.png",

			IsEng: false,
		},
		{
			PlatformName:    "Goodpatch",
			FeedName:        "Goodpatch Blog グッドパッチブログ",
			FeedDescription: "Goodpatchが運営するブログです。主にUI/UXデザインや、デザインパートナーとしての事例、デザイン思考に関するナレッジ、社内のイベントやカルチャー発信、Prott、Strap、ReDesignerなど自社サービスの紹介も行っています。",
			FeedThumbnail:   "https://goodpatch.com/assets/ogp.png",
			seedCategoryID:  1,
			RssURL:          "https://goodpatch.com/blog/feed/",

			PlatformSiteURL: "https://goodpatch.com/blog/",
			FeedSiteURL:     "https://goodpatch.com/blog/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://goodpatch.com/apple-touch-icon.png",

			IsEng: false,
		},
		{
			PlatformName:    "Dropbox",
			FeedName:        "Dropbox Tech Blog",
			FeedDescription: "Dropbox Tech Blog",
			FeedThumbnail:   "https://cfl.dropboxstatic.com/static/metaserver/static/images/logo_catalog/dropbox_opengraph_image%402x.png",
			seedCategoryID:  1,
			RssURL:          "https://dropbox.tech/feed",

			PlatformSiteURL: "https://dropbox.tech/",
			FeedSiteURL:     "https://dropbox.tech/",
			PlatformType:    domain.PlatformTypeCompany,
			FaviconURL:      "https://dropbox.tech/cms/content/dam/dropbox/aem/favicon32.ico",

			IsEng: true,
		},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "Engineering | Uber Blog",
		//	FeedDescription: "The technology behind Uber Engineering",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  1,
		//	RssURL:          "https://www.uber.com/en-JP/blog/engineering/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/en-JP/blog/engineering/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "AI | Uber Blog",
		//	FeedDescription: "Uber AI is at the heart of AI-powered innovation and technologies at Uber. AI research and its applications solve challenges across the whole of Uber.",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  52,
		//	RssURL:          "https://www.uber.com/blog/engineering/ai/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/blog/engineering/ai/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "Backend | Uber Blog",
		//	FeedDescription: "Uber Engineering's backend technologies",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  53,
		//	RssURL:          "https://www.uber.com/blog/engineering/backend/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/blog/engineering/backend/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "Data / ML | Uber Blog",
		//	FeedDescription: "Uber Engineering's data and machine learning technologies",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  33,
		//	RssURL:          "https://www.uber.com/blog/engineering/data/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/blog/engineering/data/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "Mobile | Uber Blog",
		//	FeedDescription: "Uber Engineering's mobile technologies",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  54,
		//	RssURL:          "https://www.uber.com/blog/engineering/mobile/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/blog/engineering/mobile/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		//{
		//	PlatformName:    "Uber",
		//	FeedName:        "Web | Uber Blog",
		//	FeedDescription: "Uber Engineering's web technologies",
		//	FeedThumbnail:   "https://blog.uber-cdn.com/cdn-cgi/image/width=2160,quality=80,onerror=redirect,format=auto/wp-content/uploads/2018/09/uber_blog_seo.png",
		//	seedCategoryID:  43,
		//	RssURL:          "https://www.uber.com/blog/engineering/web/rss/",
		//	PlatformSiteURL: "https://www.uber.com/en-JP/blog/engineering/",
		//	FeedSiteURL:     "https://www.uber.com/blog/engineering/web/",
		//	PlatformType:    domain.PlatformTypeCompany,
		//	FaviconURL:      "https://d3i4yxtzktqr9n.cloudfront.net/ubercom-dynamic/c4de46a6cbd165a9.png",
		//	IsEng:           true,
		//},
		{
			PlatformName:      "Dev Community",
			FeedName:          "React | Dev Community",
			FeedDescription:   "React is a JavaScript library for building user interfaces. Learn what React is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    18,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/react/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComReact,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Next.js | Dev Community",
			FeedDescription:   "Next.js is a React framework that enables functionality such as server-side rendering and generating static websites for React based web applications. Learn what Next.js is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    20,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/nextjs/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComNextjs,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "ReactNative | Dev Community",
			FeedDescription:   "React Native is a framework for building native apps using React. Learn what React Native is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    26,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/reactnative/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComReactNative,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Node.js | Dev Community",
			FeedDescription:   "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine. Learn what Node.js is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    22,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/node/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComNodejs,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "TypeScript | Dev Community",
			FeedDescription:   "TypeScript is a superset of JavaScript that compiles to plain JavaScript. Learn what TypeScript is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    6,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/typescript/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComuTypescript,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Go | Dev Community",
			FeedDescription:   "Go is an open-source programming language that makes it easy to build simple, reliable, and efficient software. Learn what Go is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    9,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/Go/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComGo,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "AWS | Dev Community",
			FeedDescription:   "Amazon Web Services (AWS) is a secure cloud services platform, offering compute power, database storage, content delivery and other functionality to help businesses scale and grow. Learn what AWS is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    28,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/aws/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComAWS,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "GCP | Dev Community",
			FeedDescription:   "Google Cloud Platform (GCP) is a suite of cloud computing services that runs on the same infrastructure that Google uses internally for its end-user products, such as Google Search, Gmail, file storage, and YouTube. Learn what GCP is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    29,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/googlecloud/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComGCP,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Docker | Dev Community",
			FeedDescription:   "Docker is an open platform for developing, shipping, and running applications. Docker enables you to separate your applications from your infrastructure so you can deliver software quickly. Learn what Docker is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    31,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/docker/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComDocker,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Testing | Dev Community",
			FeedDescription:   "Testing is an essential part of software development. Learn what Testing is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    44,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/testing/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComTesting,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "GraphQL | Dev Community",
			FeedDescription:   "GraphQL is a query language for APIs and a runtime for executing those queries by using a type system you define for your data. Learn what GraphQL is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    36,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/graphql/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComGraphQL,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Frontend | Dev Community",
			FeedDescription:   "Frontend development is the practice of producing HTML, CSS, and JavaScript for a website or web application so that a user can see and interact with them directly. Learn what Front end is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    43,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/frontend/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComFrontendDevelopment,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Web Development | Dev Community",
			FeedDescription:   "Web development is the practice of building interactive web applications. Learn what Web Development is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    4,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/webdev/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComWebDevelopment,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "AI | Dev Community",
			FeedDescription:   "Artificial intelligence (AI) is the simulation of human intelligence processes by machines, especially computer systems. Learn what AI is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    52,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/ai/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComAI,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Machine Learning | Dev Community",
			FeedDescription:   "Machine learning is a method of data analysis that automates analytical model building. Learn what Machine Learning is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    33,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/machinelearning/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComMachineLearning,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "Programming | Dev Community",
			FeedDescription:   "Programming is the process of creating a set of instructions that tell a computer how to perform a task. Learn what Programming is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    4,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/programming/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComPrograming,
		},
		{
			PlatformName:      "Dev Community",
			FeedName:          "DevOps | Dev Community",
			FeedDescription:   "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). Learn what DevOps is all about on DEV.",
			FeedThumbnail:     "https://dev-to-uploads.s3.amazonaws.com/uploads/articles/8lvvnvil0m75nw7yi6iz.jpg",
			seedCategoryID:    40,
			RssURL:            "https://dev.to/feed",
			PlatformSiteURL:   "https://dev.to/",
			FeedSiteURL:       "https://dev.to/t/devops/top/week",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://dev-to.s3.us-east-2.amazonaws.com/favicon.ico",
			IsEng:             true,
			TrendPlatformType: &devCommunityTrendType,
			APIQueryParam:     &devComDevops,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Hashnode",
			FeedDescription:   "Hashnode is a free developer blogging platform that allows you to publish articles on your own domain and helps you stay connected with a global developer community.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    1,
			RssURL:            "https://hashnode.com/n/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "React | Hashnode",
			FeedDescription:   "React is a JavaScript library for building user interfaces.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    18,
			RssURL:            "https://hashnode.com/n/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/reactjs",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeReact,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Next.js | Hashnode",
			FeedDescription:   "Next.js - The React Framework",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    20,
			RssURL:            "https://hashnode.com/n/nextjs/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/nextjs/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeNextjs,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "React Native | Hashnode",
			FeedDescription:   "React Native - Learn once, write anywhere: Build mobile apps with React",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    26,
			RssURL:            "https://hashnode.com/n/react-native/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/react-native/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeReactNative,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Node.js | Hashnode",
			FeedDescription:   "Node.js - Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    22,
			RssURL:            "https://hashnode.com/n/nodejs/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/nodejs/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeNodejs,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "TypeScript | Hashnode",
			FeedDescription:   "TypeScript  - TypeScript is an open-source language which builds on JavaScript, one of the world's most used tools, by adding static type definitions.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    6,
			RssURL:            "https://hashnode.com/n/typescript/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/typescript/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeTypescript,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Go | Hashnode",
			FeedDescription:   "Go Language   - Go is an open source programming language that makes it easy to build simple, reliable, and efficient software.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    9,
			RssURL:            "https://hashnode.com/n/go/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/go/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeGo,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "AWS | Hashnode",
			FeedDescription:   "AWS   - Amazon Web Services offers reliable, scalable, and inexpensive cloud computing services.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    28,
			RssURL:            "https://hashnode.com/n/aws/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/aws/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeAWS,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "GCP | Hashnode",
			FeedDescription:   "GCP   - Google Cloud Platform lets you build, deploy, and scale applications, websites, and services on the same infrastructure as Google.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    29,
			RssURL:            "https://hashnode.com/n/gcp/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/gcp/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeGCP,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Docker | Hashnode",
			FeedDescription:   "Docker - Docker is a computer program that performs operating-system-level virtualization also known as containerization. It is developed by Docker, Inc.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    31,
			RssURL:            "https://hashnode.com/n/docker/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/docker/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeDocker,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Testing | Hashnode",
			FeedDescription:   "Testing - Software testing is an investigation conducted to provide stakeholders with information about the quality of the software product or service under test.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    44,
			RssURL:            "https://hashnode.com/n/testing/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/testing/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeTesting,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "GraphQL | Hashnode",
			FeedDescription:   "GraphQL - GraphQL is a data query language developed internally by Facebook in 2012 before being publicly released in 2015. It provides an alternative to REST and ad-hoc webservice architectures.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    36,
			RssURL:            "https://hashnode.com/n/graphql/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/graphql/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeGraphQL,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Frontend Development | Hashnode",
			FeedDescription:   "Frontend Development - Front-end web development, also known as client-side development is the practice of producing HTML, CSS and JavaScript for a website or Web Application so that a user can see and interact with them directly.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    43,
			RssURL:            "https://hashnode.com/n/frontend-development/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/frontend-development/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeFrontendDevelopment,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Web Development | Hashnode",
			FeedDescription:   "Web Development - Web development is the work involved in developing a Web site for the Internet or an intranet.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    4,
			RssURL:            "https://hashnode.com/n/web-development/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/web-development/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeWebDevelopment,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "ChatGPT | Hashnode",
			FeedDescription:   "ChatGPT - ChatGPT is a large language model that can generate human-like responses to given prompts.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    41,
			RssURL:            "https://hashnode.com/n/chatgpt/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/chatgpt/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeChatGPT,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Developer | Hashnode",
			FeedDescription:   "Developer - A developer is a person who writes computer software.",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    4,
			RssURL:            "https://hashnode.com/n/developer/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/developer/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeDeveloper,
		},
		{
			PlatformName:      "Hashnode",
			FeedName:          "Devops | Hashnode",
			FeedDescription:   "Devops - Processes and tools that help DEV and OPS teams work faster",
			FeedThumbnail:     "https://cdn.hashnode.com/res/hashnode/image/upload/v1697709257859/6413332e-a3c0-4d37-bc72-f65293cb6664.png",
			seedCategoryID:    46,
			RssURL:            "https://hashnode.com/n/devops/rss",
			PlatformSiteURL:   "https://hashnode.com/",
			FeedSiteURL:       "https://hashnode.com/n/devops/",
			PlatformType:      domain.PlatformTypeSite,
			FaviconURL:        "https://cdn.hashnode.com/res/hashnode/image/upload/v1611242155728/W3_BYVVVh.png",
			IsEng:             true,
			TrendPlatformType: &hashnodeTrendType,
			APIQueryParam:     &hashnodeDevops,
		},
	}
}
