import { Inter } from "next/font/google";

import { BaseLayout } from "@/components/layout/BaseLayout";

import { Providers } from "./provider";

import type { Metadata } from "next";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Providers>
          <BaseLayout> {children}</BaseLayout>
        </Providers>
      </body>
    </html>
  );
}
