export const NAVIGATION_LISTS = {
  HOME: "/",
  DASHBOARD_TREND: "/dashboard/trend",
  DASHBOARD_SITE: "/dashboard/site",
  DASHBOARD_COMPANY: "/dashboard/company",
  DASHBOARD_SUMMARY: "/dashboard/summary",
  BOOKMARK: "/bookmark",
  ARTICLE_SEARCH: "/article/search",
  ARTICLE_SEARCH_RESULT: "/article/search/result",
  FEED: "/feed",
  MY_FEED_FOLDER: "/my-feed",
  MY_FEED_FOLDER_ARTICLE: "/my-feed/article",
  FAVORITE_ARTICLE_FOLDER: "/favorite",
  FAVORITE_ARTICLE_FOLDER_ARTICLE: "/favorite/article",
};
