on:
  pull_request:
    types: [opened]
name: Pull Request
jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    timeout-minutes: 10 # job全体
    steps:
      - name: Label PR
        uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'