name: mobile_rn_client_pr_check

on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"
      - "feat/*"
      - "YL-*"
    paths:
      - "mobile/rn-client/**"
      - ".github/workflows/mobile_rn_client_pr_check.yml"
#
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    defaults:
      run:
        working-directory: ./mobile/rn-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./web/client/package-lock.json

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Lint
        run: npm run lint
      
      - name: Test
        run: npm run test:ci

    #   - name: Build
    #     run: npm run build
